# Generated by kiln golden from .rn-forge/kiln/config.toml — do not edit; run 'kiln apply'
"""Enforce the archetype's rn-forge dependency contract.

An archetype is not only a repo shape — it is also the set of shared libraries a
repo of that shape is built on (kiln ADR-0009). A `python-cli` repo gets commons
and tooling; a `python-web` repo gets its backend framework package as well.
That is the whole point of naming archetypes: the boilerplate a repo does not
write is the boilerplate it takes from the component libraries.

Three rules, all read from `pyproject.toml` with `tomllib` and nothing else, so
a cold clone can run this with the pinned interpreter alone:

1. **Required.** Every distribution in REQUIRED is a runtime dependency of at
   least one distributable in this repo.
2. **Allowed.** No `rn-forge-*` distribution outside ALLOWED appears anywhere —
   dependencies, optional dependencies or dependency groups. This is the
   dependency-level form of the import boundary (kiln ADR-0003): import-linter
   cannot express "this external subpackage but not that one", and the honest
   place to draw the line is where the dependency is declared.
3. **Pinned.** Every rn-forge `[tool.uv.sources]` entry resolves to a tag or a
   rev, never a bare branch. pykit publishes GitHub Releases rather than to
   PyPI, so a git source is normal here — a *moving* git source is not, because
   it makes a build unreproducible without changing a single tracked byte.

Usage: check_rn_forge_deps.py [repo-root]   (default: current directory)
"""

from __future__ import annotations

import re
import sys
import tomllib
from pathlib import Path

# BEGIN kiln config
# Distributions this repo must depend on, from its archetype's defaults.
REQUIRED = ["rn-forge-commons"]
# Every rn-forge distribution this repo may depend on, for any purpose.
ALLOWED = ["rn-forge-commons", "rn-forge-tooling"]
# Every pyproject.toml in the repo: the root, plus each workspace member.
PYPROJECT_PATHS = ["pyproject.toml"]
# END kiln config

RN_FORGE_PREFIX = "rn-forge-"
# A PEP 508 requirement's distribution name: everything before the first extra,
# specifier, marker or whitespace. `rn-forge-django[codegen]>=0.2` → `rn-forge-django`.
REQUIREMENT_NAME = re.compile(r"^\s*([A-Za-z0-9][A-Za-z0-9._-]*)")


def distribution(requirement: str) -> str:
    match = REQUIREMENT_NAME.match(requirement)
    return match.group(1).lower().replace("_", "-") if match else ""


def runtime_dependencies(document: dict[str, object]) -> list[str]:
    project = document.get("project")
    if not isinstance(project, dict):
        return []
    dependencies = project.get("dependencies")
    return [d for d in dependencies if isinstance(d, str)] if isinstance(dependencies, list) else []


def every_dependency(document: dict[str, object]) -> list[str]:
    """Runtime, optional and dependency-group requirements, flattened.

    A dependency group is still a dependency: a kit that a repo installs only to
    develop with is exactly the coupling ADR-0003 is about.
    """
    found = list(runtime_dependencies(document))

    project = document.get("project")
    if isinstance(project, dict):
        optional = project.get("optional-dependencies")
        if isinstance(optional, dict):
            for requirements in optional.values():
                if isinstance(requirements, list):
                    found.extend(r for r in requirements if isinstance(r, str))

    groups = document.get("dependency-groups")
    if isinstance(groups, dict):
        for requirements in groups.values():
            if isinstance(requirements, list):
                # `{ include-group = "…" }` entries are references, not requirements.
                found.extend(r for r in requirements if isinstance(r, str))

    return found


def uv_sources(document: dict[str, object]) -> dict[str, object]:
    tool = document.get("tool")
    if not isinstance(tool, dict):
        return {}
    uv = tool.get("uv")
    if not isinstance(uv, dict):
        return {}
    sources = uv.get("sources")
    return sources if isinstance(sources, dict) else {}


def check_allowed(label: str, document: dict[str, object]) -> list[str]:
    allowed = {name.lower() for name in ALLOWED}
    return [
        f"{label}: depends on `{distribution(requirement)}`, which is not in this "
        f"archetype's allowed set {sorted(allowed)} — an rn-forge kit is a "
        f"subprocess, never a dependency"
        for requirement in every_dependency(document)
        if distribution(requirement).startswith(RN_FORGE_PREFIX)
        and distribution(requirement) not in allowed
    ]


def check_pinned(label: str, document: dict[str, object]) -> list[str]:
    errors: list[str] = []
    for name, source in uv_sources(document).items():
        if not name.lower().startswith(RN_FORGE_PREFIX) or not isinstance(source, dict):
            continue
        if "git" not in source:
            continue  # a workspace or path source is pinned by definition
        if "tag" not in source and "rev" not in source:
            errors.append(
                f"{label}: [tool.uv.sources.{name}] is a git source with no `tag` or "
                f"`rev` — pin it, or the build changes without the repo changing"
            )
    return errors


def main() -> int:
    root = Path(sys.argv[1] if len(sys.argv) > 1 else ".").resolve()

    errors: list[str] = []
    declared: set[str] = set()

    for relative in PYPROJECT_PATHS:
        path = root / relative
        if not path.exists():
            errors.append(f"{relative}: not found — the archetype expects it")
            continue
        document = tomllib.loads(path.read_text(encoding="utf-8"))
        errors.extend(check_allowed(relative, document))
        errors.extend(check_pinned(relative, document))
        declared.update(distribution(r) for r in runtime_dependencies(document))

    errors.extend(
        f"pyproject.toml: this archetype requires a dependency on `{name}`, and no "
        f"distributable in this repo declares one"
        for name in REQUIRED
        if name.lower() not in declared
    )

    if errors:
        for error in errors:
            print(error)
        return 1

    return 0


if __name__ == "__main__":
    sys.exit(main())
