# Generated by kiln golden from .rn-forge/kiln/config.toml — do not edit; run 'kiln apply'
"""Enforce the archetype's rn-forge dependency contract.

An archetype is not only a repo shape — it is also the set of shared libraries a
repo of that shape is built on (kiln ADR-0005). A `python-cli` repo gets commons
and tooling; a `python-django-ng` or `python-fastapi-ng` repo gets its framework
package as well.
That is the whole point of naming archetypes: the boilerplate a repo does not
write is the boilerplate it takes from the component libraries.

Three rules, all read from `pyproject.toml` with `tomllib` and nothing else, so
a cold clone can run this with the pinned interpreter alone:

1. **Required.** Every distribution in REQUIRED is a runtime dependency of at
   least one distributable in this repo.
2. **Allowed.** No `rn-forge-*` distribution outside ALLOWED appears anywhere —
   dependencies, optional dependencies or dependency groups. This is the
   dependency-level form of the import boundary (kiln ADR-0002): import-linter
   cannot express "this external subpackage but not that one", and the honest
   place to draw the line is where the dependency is declared.
3. **Pinned, and in the published metadata.** Every rn-forge requirement is a
   PEP 508 direct URL naming a tag or a rev:

       rn-forge-commons @ git+https://github.com/rn-forge/pykit@rn-forge-commons-v0.2.2#subdirectory=packages/rn-forge-commons

   `[tool.uv.sources]` would be simpler to read, and it is what a workspace
   reaches for first — but it is a *local* override that does not survive into a
   built wheel. A consumer installing this repo's release would then be told to
   find `rn-forge-commons` on an index it is not published to. The URL in
   `dependencies` is the only form that ships with the package.

   The trade is deliberate: a distribution with a direct reference cannot be
   uploaded to PyPI, and the version floor is gone because a requirement cannot
   carry both a URL and a specifier. The tag *is* the version.

Usage: check_rn_forge_deps.py [repo-root]   (default: current directory)
"""

from __future__ import annotations

import re
import sys
import tomllib
from pathlib import Path

# BEGIN kiln config
# Distributions this repo must depend on, from its archetype's defaults.
REQUIRED = ["rn-forge-commons"]
# Every rn-forge distribution this repo may depend on, for any purpose.
ALLOWED = ["rn-forge-commons", "rn-forge-tooling"]
# Every pyproject.toml in the repo: the root, plus each workspace member.
PYPROJECT_PATHS = [
    "pyproject.toml",
    "packages/golden-alpha/pyproject.toml",
    "packages/golden-beta/pyproject.toml",
]
# END kiln config

RN_FORGE_PREFIX = "rn-forge-"
# A PEP 508 requirement's distribution name: everything before the first extra,
# specifier, marker or whitespace. `rn-forge-django[codegen]>=0.2` → `rn-forge-django`.
REQUIREMENT_NAME = re.compile(r"^\s*([A-Za-z0-9][A-Za-z0-9._-]*)")
# A git URL carrying a ref: `git+https://host/org/repo@<ref>`, with the ref
# ending at the `#subdirectory=` fragment if there is one.
PINNED_GIT_URL = re.compile(r"^git\+[^@\s]+@[^#\s]+")


def distribution(requirement: str) -> str:
    match = REQUIREMENT_NAME.match(requirement)
    return match.group(1).lower().replace("_", "-") if match else ""


def runtime_dependencies(document: dict[str, object]) -> list[str]:
    project = document.get("project")
    if not isinstance(project, dict):
        return []
    dependencies = project.get("dependencies")
    return (
        [d for d in dependencies if isinstance(d, str)]
        if isinstance(dependencies, list)
        else []
    )


def every_dependency(document: dict[str, object]) -> list[str]:
    """Runtime, optional and dependency-group requirements, flattened.

    A dependency group is still a dependency: a kit that a repo installs only to
    develop with is exactly the coupling ADR-0002 is about.
    """
    found = list(runtime_dependencies(document))

    project = document.get("project")
    if isinstance(project, dict):
        optional = project.get("optional-dependencies")
        if isinstance(optional, dict):
            for requirements in optional.values():
                if isinstance(requirements, list):
                    found.extend(r for r in requirements if isinstance(r, str))

    groups = document.get("dependency-groups")
    if isinstance(groups, dict):
        for requirements in groups.values():
            if isinstance(requirements, list):
                # `{ include-group = "…" }` entries are references, not requirements.
                found.extend(r for r in requirements if isinstance(r, str))

    return found


def uv_sources(document: dict[str, object]) -> dict[str, object]:
    tool = document.get("tool")
    if not isinstance(tool, dict):
        return {}
    uv = tool.get("uv")
    if not isinstance(uv, dict):
        return {}
    sources = uv.get("sources")
    return sources if isinstance(sources, dict) else {}


def check_allowed(label: str, document: dict[str, object]) -> list[str]:
    allowed = {name.lower() for name in ALLOWED}
    return [
        f"{label}: depends on `{distribution(requirement)}`, which is not in this "
        f"archetype's allowed set {sorted(allowed)} — an rn-forge kit is a "
        f"subprocess, never a dependency"
        for requirement in every_dependency(document)
        if distribution(requirement).startswith(RN_FORGE_PREFIX)
        and distribution(requirement) not in allowed
    ]


def check_direct_url(label: str, document: dict[str, object]) -> list[str]:
    """Every rn-forge requirement carries its own pinned source."""
    errors: list[str] = []
    for requirement in every_dependency(document):
        name = distribution(requirement)
        if not name.startswith(RN_FORGE_PREFIX):
            continue
        url = requirement.partition(" @ ")[2].strip()
        if not url:
            errors.append(
                f"{label}: `{name}` is declared without a direct URL — a "
                f"[tool.uv.sources] override does not survive into a built wheel, "
                f"so a consumer of this package could not resolve it"
            )
            continue
        if not PINNED_GIT_URL.match(url):
            errors.append(
                f"{label}: `{name}` resolves to {url!r}, which names no tag or rev — "
                f"pin it, or the build changes without the repo changing"
            )
    return errors


def check_no_shadowing_source(label: str, document: dict[str, object]) -> list[str]:
    """A [tool.uv.sources] entry for an rn-forge package hides the real one.

    It would resolve locally and silently disagree with what the wheel says, which
    is the failure this whole rule exists to prevent.
    """
    return [
        f"{label}: [tool.uv.sources.{name}] overrides an rn-forge dependency — "
        f"remove it and pin the URL in `dependencies` instead"
        for name in uv_sources(document)
        if name.lower().startswith(RN_FORGE_PREFIX)
    ]


def main() -> int:
    root = Path(sys.argv[1] if len(sys.argv) > 1 else ".").resolve()

    errors: list[str] = []
    declared: set[str] = set()

    for relative in PYPROJECT_PATHS:
        path = root / relative
        if not path.exists():
            errors.append(f"{relative}: not found — the archetype expects it")
            continue
        document = tomllib.loads(path.read_text(encoding="utf-8"))
        errors.extend(check_allowed(relative, document))
        errors.extend(check_direct_url(relative, document))
        errors.extend(check_no_shadowing_source(relative, document))
        declared.update(distribution(r) for r in runtime_dependencies(document))

    errors.extend(
        f"pyproject.toml: this archetype requires a dependency on `{name}`, and no "
        f"distributable in this repo declares one"
        for name in REQUIRED
        if name.lower() not in declared
    )

    if errors:
        for error in errors:
            print(error)
        return 1

    return 0


if __name__ == "__main__":
    sys.exit(main())
