# Generated by kiln golden from .rn-forge/kiln/config.toml — do not edit; run 'kiln apply'
"""Verify the working tree still matches the committed kiln state baseline.

This is the CI half of the generation model: kiln is a developer-only tool and
never runs in CI, so what CI checks is the committed `.rn-forge/kiln/state.json`
against the bytes on disk. It renders nothing and imports nothing outside the
standard library, so a cold clone can run it with the pinned interpreter alone.

Three artifact kinds, three questions:

- `managed` — the whole file is kiln's. Its SHA-256 must equal the recorded one.
- `block`   — kiln owns a fenced region inside a repo-owned file. The region
              must be present and its body's SHA-256 must equal the recorded one.
- `seeded`  — kiln wrote the file once and never touches it again. It must exist;
              its content is nobody's business here.

What this cannot see is whether a *newer kiln* would render something different.
That is `kiln doctor`'s job, and it is deliberately not CI's.

Usage: check_generated.py [repo-root]   (default: current directory)
"""

from __future__ import annotations

import hashlib
import json
import sys
from pathlib import Path

STATE_PATH = Path(".rn-forge/kiln/state.json")
SCHEMA_VERSION = 1


def digest(data: bytes) -> str:
    return "sha256:" + hashlib.sha256(data).hexdigest()


def block_body(text: str, begin_marker: str, end_marker: str) -> str | None:
    """The lines strictly between the two markers, or None if either is missing.

    Markers are compared stripped, so an indented fence (mkdocs.yml's nav block)
    matches the same way a column-zero one does.
    """
    begin = begin_marker.strip()
    end = end_marker.strip()
    begin_index: int | None = None
    end_index: int | None = None
    lines = text.splitlines()
    for index, line in enumerate(lines):
        stripped = line.strip()
        if stripped == begin and begin_index is None:
            begin_index = index
        elif stripped == end and begin_index is not None:
            end_index = index
            break
    if begin_index is None or end_index is None:
        return None
    return "\n".join(lines[begin_index + 1 : end_index])


def check_managed(root: Path, key: str, entry: dict[str, object]) -> list[str]:
    path = root / str(entry["path"])
    if not path.exists():
        return [f"{entry['path']}: managed artifact is missing — run `kiln apply`"]
    actual = digest(path.read_bytes())
    if actual != entry["content_hash"]:
        return [
            (
                f"{entry['path']}: managed artifact has drifted from the committed "
                f"state ({actual} != {entry['content_hash']}) — run `kiln apply` "
                f"or revert the edit"
            )
        ]
    return []


def check_block(root: Path, key: str, entry: dict[str, object]) -> list[str]:
    path = root / str(entry["path"])
    if not path.exists():
        return [f"{entry['path']}: file holding managed block {key!r} is missing"]
    body = block_body(
        path.read_text(encoding="utf-8"),
        str(entry["begin_marker"]),
        str(entry["end_marker"]),
    )
    if body is None:
        return [
            (
                f"{entry['path']}: managed block {entry['begin_marker']!r} is "
                f"missing — run `kiln apply`"
            )
        ]
    actual = digest(body.encode("utf-8"))
    if actual != entry["content_hash"]:
        return [
            (
                f"{entry['path']}: managed block {entry['begin_marker']!r} has "
                f"drifted ({actual} != {entry['content_hash']}) — run `kiln apply` "
                f"or revert the edit"
            )
        ]
    return []


def check_seeded(root: Path, key: str, entry: dict[str, object]) -> list[str]:
    path = root / str(entry["path"])
    if not path.exists():
        return [f"{entry['path']}: seeded artifact is missing — run `kiln apply`"]
    return []


CHECKS = {"managed": check_managed, "block": check_block, "seeded": check_seeded}


def main() -> int:
    root = Path(sys.argv[1] if len(sys.argv) > 1 else ".").resolve()
    state_path = root / STATE_PATH

    if not state_path.exists():
        print(f"{STATE_PATH}: not found — this is not a kiln repo")
        return 1

    state = json.loads(state_path.read_text(encoding="utf-8"))
    if state.get("schema_version") != SCHEMA_VERSION:
        print(
            f"{STATE_PATH}: schema_version is {state.get('schema_version')!r}, "
            f"expected {SCHEMA_VERSION} — upgrade kiln and re-run `kiln apply`"
        )
        return 1

    errors: list[str] = []
    for key, entry in sorted(state.get("entries", {}).items()):
        kind = entry.get("kind")
        if kind not in CHECKS:
            errors.append(f"{STATE_PATH}: entry {key!r} has unknown kind {kind!r}")
            continue
        if Path(str(entry["path"])) == STATE_PATH:
            errors.append(f"{STATE_PATH}: state must not hash itself (entry {key!r})")
            continue
        errors.extend(CHECKS[kind](root, key, entry))

    if errors:
        for error in errors:
            print(error)
        return 1

    return 0


if __name__ == "__main__":
    sys.exit(main())
