"""S4.3.3 — the `tasks` module's artifacts: `Taskfile.yml`, `tasks/*.yml`, includes.

Also proves the five properties every F4.3 story owes its module
(`docs/specs/epics/E4-generator/F4.3-concern-modules.md`).
"""

from __future__ import annotations

import json
import re
import subprocess
from pathlib import Path

import pytest
from rn_forge.commons.exceptions import AppException
from rn_forge.tooling.generation import Action, ArtifactKind

from rn_forge.kiln.config import KilnConfig
from rn_forge.kiln.modules.core import cycle
from rn_forge.kiln.modules.tasks import TASKS
from rn_forge.kiln.modules.tasks.checks import layout

GOLDEN = Path(__file__).resolve().parents[2] / "fixtures" / "golden"
ARCHETYPES = ("python-app", "python-tool", "python-lib")

TASK_KEYS = (
    "Taskfile.yml",
    "tasks/workspace.yml",
    "tasks/quality.yml",
    "tasks/docs.yml",
)

CONFIG = """
schema_version = 1

[repository]
name = "demo"
archetype = "{archetype}"

[docs]
profile = "{profile}"
{extra}
"""

PACKAGES = """
[archetype."python-lib"]
packages = ["packages/alpha", "packages/beta"]
"""

INCLUDE_EXTRA = (
    '\n[tasks]\nincludes = [{ namespace = "ci", taskfile = "tasks/ci.yml" }]\n'
)


def _root(
    tmp_path: Path,
    archetype: str = "python-tool",
    profile: str = "mkdocs",
    extra: str = "",
) -> Path:
    config = tmp_path / ".rn-forge" / "kiln" / "config.toml"
    config.parent.mkdir(parents=True)
    text = CONFIG.format(archetype=archetype, profile=profile, extra=extra)
    if archetype == "python-lib":
        text += PACKAGES
    config.write_text(text, encoding="utf-8")
    return tmp_path


def _actions(root: Path, tmp_path: Path) -> dict[str, Action]:
    return {
        change.key: change.action
        for change in cycle.plan(root, home=tmp_path / "home").changes
    }


def _codes(root: Path) -> list[str]:
    return sorted(f.code for f in TASKS.checks(KilnConfig.load(root), root))


def _run_task(root: Path, *args: str) -> subprocess.CompletedProcess[str]:
    return subprocess.run(
        ["task", *args], cwd=root, capture_output=True, text=True, check=False
    )


@pytest.mark.parametrize("archetype", ARCHETYPES)
def test_s4_3_3_property1_renders_exactly_the_module_s_template_inventory_rows(
    tmp_path: Path, archetype: str
) -> None:
    root = _root(tmp_path, archetype)
    artifacts = TASKS.artifacts(KilnConfig.load(root), root)
    assert [(a.path, a.kind) for a in artifacts] == [
        (path, ArtifactKind.MANAGED) for path in TASK_KEYS
    ]


def test_s4_3_3_property1_without_mkdocs_omits_docs_yml(tmp_path: Path) -> None:
    root = _root(tmp_path, profile="none")
    artifacts = TASKS.artifacts(KilnConfig.load(root), root)
    assert [a.path for a in artifacts] == list(TASK_KEYS[:-1])


def test_s4_3_3_property1_one_seeded_artifact_per_include(tmp_path: Path) -> None:
    root = _root(tmp_path, extra=INCLUDE_EXTRA)
    artifacts = TASKS.artifacts(KilnConfig.load(root), root)
    assert [a.path for a in artifacts] == [*TASK_KEYS, "tasks/ci.yml"]
    assert artifacts[-1].kind is ArtifactKind.SEEDED


@pytest.mark.parametrize("archetype", ARCHETYPES)
def test_s4_3_3_property2_into_an_empty_directory_only_creates(
    tmp_path: Path, archetype: str
) -> None:
    actions = _actions(_root(tmp_path, archetype), tmp_path)
    tasks_actions = {key: actions[key] for key in TASK_KEYS}
    assert set(tasks_actions.values()) == {Action.CREATE}


@pytest.mark.parametrize("archetype", ARCHETYPES)
def test_s4_3_3_property3_a_second_apply_is_unchanged(
    tmp_path: Path, archetype: str
) -> None:
    root = _root(tmp_path, archetype)
    cycle.apply(root, home=tmp_path / "home")
    actions = _actions(root, tmp_path)
    assert all(actions[key] is Action.UNCHANGED for key in TASK_KEYS)


def test_s4_3_3_property3_an_include_reports_skip_once_present(tmp_path: Path) -> None:
    root = _root(tmp_path, extra=INCLUDE_EXTRA)
    cycle.apply(root, home=tmp_path / "home")
    assert _actions(root, tmp_path)["tasks/ci.yml"] is Action.SKIP


def _normalized(text: str) -> str:
    """Drop the provenance line's kiln version, the only line that never matches."""
    return re.sub(
        r"^# Generated by kiln .*$",
        "# Generated by kiln X",
        text,
        count=1,
        flags=re.M,
    )


@pytest.mark.parametrize("archetype", ARCHETYPES)
def test_s4_3_3_property4_matches_its_golden(tmp_path: Path, archetype: str) -> None:
    """Every golden's `[tasks].includes` is empty, so only the managed rows apply."""
    golden = GOLDEN / archetype
    config = KilnConfig.load(golden)
    rendered = {a.path: a.content for a in TASKS.artifacts(config, golden)}
    for path in TASK_KEYS:
        on_disk = (golden / path).read_text(encoding="utf-8")
        assert _normalized(rendered[path]) == _normalized(on_disk), path


@pytest.mark.parametrize("archetype", ARCHETYPES)
def test_s4_3_3_property5_task_layout_passes_on_the_rendered_output(
    tmp_path: Path, archetype: str
) -> None:
    root = _root(tmp_path, archetype)
    cycle.apply(root, home=tmp_path / "home")
    assert _codes(root) == []


def test_s4_3_3_property5_task_layout_fails_on_a_broken_gate(tmp_path: Path) -> None:
    root = _root(tmp_path)
    cycle.apply(root, home=tmp_path / "home")
    taskfile = root / "Taskfile.yml"
    taskfile.write_text(
        taskfile.read_text(encoding="utf-8").replace(
            "      - task: quality:test:python\n", ""
        ),
        encoding="utf-8",
    )
    assert "gate.shrunk" in _codes(root)


@pytest.mark.parametrize("archetype", ARCHETYPES)
def test_s4_3_3_1_task_list_json_lists_exactly_the_ten_root_verbs(
    tmp_path: Path, archetype: str
) -> None:
    root = _root(tmp_path, archetype, profile="none")
    cycle.apply(root, home=tmp_path / "home")
    result = _run_task(root, "--list", "--json")
    assert result.returncode == 0, result.stderr
    names = {entry["name"] for entry in json.loads(result.stdout)["tasks"]}
    assert names == {
        "setup",
        "validate",
        "lint",
        "format",
        "typecheck",
        "test",
        "test:coverage",
        "build",
        "version",
        "clean",
    }


def test_s4_3_3_1_an_mkdocs_repo_also_lists_the_four_docs_verbs(tmp_path: Path) -> None:
    root = _root(tmp_path)
    cycle.apply(root, home=tmp_path / "home")
    result = _run_task(root, "--list", "--json")
    assert result.returncode == 0, result.stderr
    names = {entry["name"] for entry in json.loads(result.stdout)["tasks"]}
    assert {"docs:build", "docs:serve", "docs:nav", "docs:structure"} <= names


def test_s4_3_3_2_a_repo_owned_include_is_seeded_once_and_list_all_succeeds(
    tmp_path: Path,
) -> None:
    root = _root(tmp_path, extra=INCLUDE_EXTRA)
    cycle.apply(root, home=tmp_path / "home")
    include = root / "tasks" / "ci.yml"
    assert include.is_file()
    result = _run_task(root, "--list-all")
    assert result.returncode == 0, result.stderr


def test_s4_3_3_2_an_edit_to_an_include_survives_apply(tmp_path: Path) -> None:
    root = _root(tmp_path, extra=INCLUDE_EXTRA)
    cycle.apply(root, home=tmp_path / "home")
    include = root / "tasks" / "ci.yml"
    edited = include.read_text(encoding="utf-8") + "  hand-written: true\n"
    include.write_text(edited, encoding="utf-8")
    assert _actions(root, tmp_path)["tasks/ci.yml"] is Action.SKIP
    cycle.apply(root, home=tmp_path / "home")
    assert include.read_text(encoding="utf-8") == edited


def test_s4_3_3_3_an_extra_ref_is_reachable_from_validate(tmp_path: Path) -> None:
    root = _root(
        tmp_path,
        extra='\n[tasks]\n[tasks.extra_refs]\nvalidate = ["workspace:clean"]\n',
    )
    cycle.apply(root, home=tmp_path / "home")
    graph, namespaces = layout.load_graph(root)
    assert "workspace:clean" in layout.reachable_from("validate", graph, namespaces)
    assert _codes(root) == []


def test_s4_3_3_3_an_unknown_extra_ref_key_fails_config_load(tmp_path: Path) -> None:
    root = _root(
        tmp_path,
        extra='\n[tasks]\n[tasks.extra_refs]\nbogus = ["workspace:clean"]\n',
    )
    with pytest.raises(AppException) as excinfo:
        KilnConfig.load(root)
    assert "tasks.extra_refs.bogus" in str(excinfo.value)


def test_s4_3_3_4_a_command_override_replaces_only_that_task_s_cmds(
    tmp_path: Path,
) -> None:
    plain = _root(tmp_path / "plain")
    overridden = _root(
        tmp_path / "overridden",
        extra=(
            '\n[tasks]\n[tasks.command_overrides]\n"quality:test:python" = "echo hi"\n'
        ),
    )
    before = {a.path: a.content for a in TASKS.artifacts(KilnConfig.load(plain), plain)}
    after = {
        a.path: a.content
        for a in TASKS.artifacts(KilnConfig.load(overridden), overridden)
    }
    assert "cmds:\n      - echo hi\n" in after["tasks/quality.yml"]
    for path in ("Taskfile.yml", "tasks/workspace.yml", "tasks/docs.yml"):
        assert after[path] == before[path]


def test_s4_3_3_4_an_unknown_override_key_raises_naming_it(tmp_path: Path) -> None:
    root = _root(
        tmp_path,
        extra='\n[tasks]\n[tasks.command_overrides]\nbogus = "echo hi"\n',
    )
    config = KilnConfig.load(root)
    with pytest.raises(AppException, match="bogus"):
        TASKS.artifacts(config, root)


WEB_CONFIG = """
schema_version = 1

[repository]
name = "demo"
archetype = "{archetype}"

[docs]
profile = "none"

[archetype."{archetype}"]
backend = "{backend}"
{extra}
"""


def _web_root(tmp_path: Path, archetype: str, backend: str, extra: str = "") -> Path:
    config = tmp_path / ".rn-forge" / "kiln" / "config.toml"
    config.parent.mkdir(parents=True)
    config.write_text(
        WEB_CONFIG.format(archetype=archetype, backend=backend, extra=extra),
        encoding="utf-8",
    )
    return tmp_path


def test_s5_1_2_python_web_api_renders_api_yml_and_no_web_yml(tmp_path: Path) -> None:
    root = _web_root(tmp_path, "python-web-api", "fastapi")
    artifacts = TASKS.artifacts(KilnConfig.load(root), root)
    paths = [a.path for a in artifacts]
    assert "tasks/api.yml" in paths
    assert "tasks/web.yml" not in paths


def test_s5_1_2_python_web_app_renders_api_yml_and_web_yml(tmp_path: Path) -> None:
    root = _web_root(
        tmp_path, "python-web-app", "fastapi", extra='frontend = "angular"'
    )
    artifacts = TASKS.artifacts(KilnConfig.load(root), root)
    paths = [a.path for a in artifacts]
    assert "tasks/api.yml" in paths
    assert "tasks/web.yml" in paths


@pytest.mark.parametrize("archetype", ["python-web-api", "python-web-app"])
def test_s5_3_1_web_ruff_commands_are_limited_to_api_src_and_tests(
    tmp_path: Path, archetype: str
) -> None:
    extra = 'frontend = "angular"' if archetype == "python-web-app" else ""
    root = _web_root(tmp_path, archetype, "fastapi", extra=extra)
    rendered = {a.path: a.content for a in TASKS.artifacts(KilnConfig.load(root), root)}
    quality = rendered["tasks/quality.yml"]
    assert "ruff check src tests" in quality
    assert "ruff format --check src tests" in quality
    assert "ruff check --fix src tests" in quality
    assert "ruff format src tests" in quality


def test_s5_1_2_task_list_json_shows_api_and_web_verbs(tmp_path: Path) -> None:
    root = _web_root(
        tmp_path, "python-web-app", "fastapi", extra='frontend = "angular"'
    )
    cycle.apply(root, home=tmp_path / "home")
    result = _run_task(root, "--list", "--json")
    assert result.returncode == 0, result.stderr
    names = {entry["name"] for entry in json.loads(result.stdout)["tasks"]}
    assert {"api:dev", "web:lint", "web:test", "web:build", "web:dev"} <= names
    assert "api:migrate" not in names  # fastapi, not django


def test_s5_1_2_django_backend_also_lists_api_migrate(tmp_path: Path) -> None:
    root = _web_root(tmp_path, "python-web-app", "django", extra='frontend = "angular"')
    cycle.apply(root, home=tmp_path / "home")
    result = _run_task(root, "--list", "--json")
    assert result.returncode == 0, result.stderr
    names = {entry["name"] for entry in json.loads(result.stdout)["tasks"]}
    assert "api:migrate" in names


def test_s5_1_2_task_layout_passes_on_both_web_archetypes(tmp_path: Path) -> None:
    for archetype, extra in (
        ("python-web-api", ""),
        ("python-web-app", 'frontend = "angular"'),
    ):
        root = _web_root(tmp_path / archetype, archetype, "fastapi", extra=extra)
        cycle.apply(root, home=tmp_path / "home")
        assert _codes(root) == [], archetype


def test_s5_1_2_gate_shrunk_fires_when_web_lint_drops_out_of_lint(
    tmp_path: Path,
) -> None:
    root = _web_root(
        tmp_path, "python-web-app", "fastapi", extra='frontend = "angular"'
    )
    cycle.apply(root, home=tmp_path / "home")
    taskfile = root / "Taskfile.yml"
    taskfile.write_text(
        taskfile.read_text(encoding="utf-8").replace("      - task: web:lint\n", ""),
        encoding="utf-8",
    )
    assert "gate.shrunk" in _codes(root)


def test_s5_1_2_a_workflow_calling_pnpm_directly_fails_ci_entrypoint(
    tmp_path: Path,
) -> None:
    from rn_forge.kiln.modules.cicd.checks import entrypoint

    root = _web_root(
        tmp_path, "python-web-app", "fastapi", extra='frontend = "angular"'
    )
    cycle.apply(root, home=tmp_path / "home")
    workflow = root / ".github" / "workflows" / "ci.yml"
    text = workflow.read_text(encoding="utf-8")
    text = text.replace(
        "      - name: Validate\n        run: task validate\n",
        "      - name: Validate\n        run: task validate\n"
        "      - name: Bad\n        run: pnpm install\n",
    )
    workflow.write_text(text, encoding="utf-8")
    findings = entrypoint.check(KilnConfig.load(root), root)
    assert any(f.code == entrypoint.CODE for f in findings)


def test_s5_1_3_backend_flag_changes_only_api_yml_and_not_the_task_graph(
    tmp_path: Path,
) -> None:
    django_root = _web_root(
        tmp_path / "django", "python-web-app", "django", extra='frontend = "angular"'
    )
    fastapi_root = _web_root(
        tmp_path / "fastapi",
        "python-web-app",
        "fastapi",
        extra='frontend = "angular"',
    )
    django_artifacts = {
        a.path: a.content
        for a in TASKS.artifacts(KilnConfig.load(django_root), django_root)
    }
    fastapi_artifacts = {
        a.path: a.content
        for a in TASKS.artifacts(KilnConfig.load(fastapi_root), fastapi_root)
    }
    assert set(django_artifacts) == set(fastapi_artifacts)
    differing = {
        path
        for path in django_artifacts
        if django_artifacts[path] != fastapi_artifacts[path]
    }
    assert differing == {"tasks/api.yml"}


def test_s4_3_3_5_without_mkdocs_the_rendered_files_carry_no_docs_reference(
    tmp_path: Path,
) -> None:
    root = _root(tmp_path, profile="none")
    cycle.apply(root, home=tmp_path / "home")
    taskfile = (root / "Taskfile.yml").read_text(encoding="utf-8")
    quality = (root / "tasks" / "quality.yml").read_text(encoding="utf-8")
    assert "docs:build" not in taskfile
    assert "docs:" not in taskfile.split("tasks:", 1)[1]
    assert "quality:lint:docs" not in taskfile
    assert "lint:docs" not in quality
    assert not (root / "tasks" / "docs.yml").exists()
    assert _codes(root) == []
