"""S4.3.5 — the `instructions` module's artifacts: the kiln block, and `standard.md`.

Also proves the five properties every F4.3 story owes its module
(`docs/specs/epics/E4-generator/F4.3-concern-modules.md`).
"""

from __future__ import annotations

import re
from pathlib import Path

import pytest
from rn_forge.tooling.generation import Action, ArtifactKind

from rn_forge.kiln.config import KilnConfig
from rn_forge.kiln.modules.core import cycle
from rn_forge.kiln.modules.docs import DOCS
from rn_forge.kiln.modules.docs.scaffold import scaffold as docs_scaffold
from rn_forge.kiln.modules.instructions import INSTRUCTIONS
from rn_forge.kiln.modules.instructions.artifacts import KILN_BLOCK
from rn_forge.kiln.modules.instructions.scaffold import scaffold

GOLDEN = Path(__file__).resolve().parents[2] / "fixtures" / "golden"
ARCHETYPES = ("python-app", "python-tool", "python-lib")

BLOCK_KEY = "CLAUDE.md#rn-forge kiln"
STANDARD = ".rn-forge/kiln/standard.md"

CONFIG = """
schema_version = 1

[repository]
name = "demo"
archetype = "{archetype}"

[docs]
profile = "{profile}"
{docs_extra}
[ci]
sonar = {sonar}
"""

PACKAGES = """
[archetype."python-lib"]
packages = ["packages/alpha", "packages/beta"]
"""


def _write_config(
    root: Path,
    archetype: str = "python-tool",
    profile: str = "mkdocs",
    sonar: bool = True,
    docs_extra: str = "",
) -> None:
    config = root / ".rn-forge" / "kiln" / "config.toml"
    config.parent.mkdir(parents=True, exist_ok=True)
    text = CONFIG.format(
        archetype=archetype,
        profile=profile,
        sonar=str(sonar).lower(),
        docs_extra=docs_extra,
    )
    if archetype == "python-lib":
        text += PACKAGES
    config.write_text(text, encoding="utf-8")


def _root(tmp_path: Path, archetype: str = "python-tool", **kwargs: object) -> Path:
    _write_config(tmp_path, archetype, **kwargs)  # type: ignore[arg-type]
    return tmp_path


def _new(tmp_path: Path, archetype: str = "python-tool", **kwargs: object) -> Path:
    """Scaffold and apply into an empty directory, as `kiln new` will."""
    root = _root(tmp_path, archetype, **kwargs)
    config = KilnConfig.load(root)
    scaffold(root, config)
    docs_scaffold(root, config)
    cycle.apply(root, home=tmp_path / "home")
    return root


def _rendered(root: Path) -> dict[str, str]:
    return {
        a.key: a.content for a in INSTRUCTIONS.artifacts(KilnConfig.load(root), root)
    }


def _actions(root: Path, tmp_path: Path) -> dict[str, Action]:
    return {
        change.key: change.action
        for change in cycle.plan(root, home=tmp_path / "home").changes
    }


def _snapshot(root: Path) -> dict[str, bytes]:
    return {
        str(path.relative_to(root)): path.read_bytes()
        for path in sorted(root.rglob("*"))
        if path.is_file()
        and ".rn-forge/kiln/backups" not in path.as_posix()
        and ".rn-forge/kiln/rendered" not in path.as_posix()
    }


@pytest.mark.parametrize("archetype", ARCHETYPES)
def test_s4_3_5_property1_renders_exactly_the_module_s_template_inventory_rows(
    tmp_path: Path, archetype: str
) -> None:
    root = _root(tmp_path, archetype)
    artifacts = INSTRUCTIONS.artifacts(KilnConfig.load(root), root)
    assert [(a.key, a.kind) for a in artifacts] == [
        (BLOCK_KEY, ArtifactKind.BLOCK),
        (STANDARD, ArtifactKind.MANAGED),
    ]
    assert artifacts[0].block == KILN_BLOCK


@pytest.mark.parametrize("archetype", ARCHETYPES)
def test_s4_3_5_property2_into_an_empty_directory_only_inserts_and_creates(
    tmp_path: Path, archetype: str
) -> None:
    actions = _actions(_root(tmp_path, archetype), tmp_path)
    assert actions[BLOCK_KEY] is Action.INSERT
    assert actions[STANDARD] is Action.CREATE


@pytest.mark.parametrize("archetype", ARCHETYPES)
def test_s4_3_5_property3_a_second_apply_is_unchanged(
    tmp_path: Path, archetype: str
) -> None:
    root = _new(tmp_path, archetype)
    actions = _actions(root, tmp_path)
    assert actions[BLOCK_KEY] is Action.UNCHANGED
    assert actions[STANDARD] is Action.UNCHANGED


def _normalized(text: str) -> str:
    """Drop the provenance line's kiln version, the only line that never matches."""
    return re.sub(r"Generated by kiln \S+ from", "Generated by kiln X from", text)


@pytest.mark.parametrize("archetype", ARCHETYPES)
def test_s4_3_5_property4_matches_its_golden(tmp_path: Path, archetype: str) -> None:
    golden = GOLDEN / archetype
    config = KilnConfig.load(golden)
    rendered = _rendered(golden)
    claude = (golden / "CLAUDE.md").read_text(encoding="utf-8")

    assert _normalized(rendered[BLOCK_KEY]) == _normalized(
        KILN_BLOCK.extract(claude) or ""
    )
    assert _normalized(rendered[STANDARD]) == _normalized(
        (golden / STANDARD).read_text(encoding="utf-8")
    )

    scaffold(tmp_path, config)
    body = (tmp_path / "CLAUDE.md").read_text(encoding="utf-8")
    assert _normalized(KILN_BLOCK.render(body, rendered[BLOCK_KEY])) == _normalized(
        claude
    )
    assert (tmp_path / "AGENTS.md").read_text(encoding="utf-8") == (
        golden / "AGENTS.md"
    ).read_text(encoding="utf-8")


@pytest.mark.parametrize("archetype", ARCHETYPES)
def test_s4_3_5_property5_root_hygiene_passes_on_the_rendered_output(
    tmp_path: Path, archetype: str
) -> None:
    root = _new(tmp_path, archetype)
    assert INSTRUCTIONS.checks(KilnConfig.load(root), root) == []


def test_s4_3_5_property5_root_hygiene_fails_on_a_stray_root_file(
    tmp_path: Path,
) -> None:
    root = _new(tmp_path)
    (root / "NOTES.md").write_text("# Notes\n", encoding="utf-8")
    codes = [f.code for f in INSTRUCTIONS.checks(KilnConfig.load(root), root)]
    assert codes == ["hygiene.stray-root-file"]


def test_s4_3_5_1_edits_to_each_body_survive_and_the_block_is_unchanged(
    tmp_path: Path,
) -> None:
    root = _new(tmp_path)
    for name in ("README.md", "CLAUDE.md", "AGENTS.md"):
        assert (root / name).is_file(), name
    edited: dict[str, str] = {}
    for name in ("README.md", "CLAUDE.md", "AGENTS.md"):
        path = root / name
        text = path.read_text(encoding="utf-8")
        edited[name] = "Hand-written first line.\n\n" + text
        path.write_text(edited[name], encoding="utf-8")

    assert _actions(root, tmp_path)[BLOCK_KEY] is Action.UNCHANGED
    config = KilnConfig.load(root)
    scaffold(root, config)
    cycle.apply(root, home=tmp_path / "home")
    for name, text in edited.items():
        assert (root / name).read_text(encoding="utf-8") == text, name


def test_s4_3_5_2_turning_sonar_off_updates_only_the_block_and_standard(
    tmp_path: Path,
) -> None:
    root = _new(tmp_path, profile="none")
    claude_before = (root / "CLAUDE.md").read_text(encoding="utf-8")
    _write_config(root, profile="none", sonar=False)

    changed = {
        key
        for key, action in _actions(root, tmp_path).items()
        if action not in (Action.UNCHANGED, Action.SKIP)
    }
    # `cicd` owns the Sonar job and properties file, so its two rows move as well.
    assert changed == {
        BLOCK_KEY,
        STANDARD,
        ".github/workflows/ci.yml",
        "sonar-project.properties",
    }

    cycle.apply(root, home=tmp_path / "home")
    claude_after = (root / "CLAUDE.md").read_text(encoding="utf-8")
    assert "Sonar off" in (KILN_BLOCK.extract(claude_after) or "")
    assert "Sonar off" in (root / STANDARD).read_text(encoding="utf-8")
    assert KILN_BLOCK.remove(claude_after) == KILN_BLOCK.remove(claude_before)


def test_s4_3_5_3_a_hand_edit_to_standard_md_is_drift(tmp_path: Path) -> None:
    root = _new(tmp_path)
    standard = root / STANDARD
    standard.write_text(
        standard.read_text(encoding="utf-8") + "\nA note.\n", encoding="utf-8"
    )
    assert _actions(root, tmp_path)[STANDARD] is Action.DRIFT


def test_s4_3_5_4_external_renders_the_url_into_the_block(tmp_path: Path) -> None:
    root = _root(
        tmp_path,
        profile="external",
        docs_extra='external_url = "https://docs.example.com/demo"\n',
    )
    block = _rendered(root)[BLOCK_KEY]
    assert "- **Docs:** external, at <https://docs.example.com/demo>.\n" in block
    assert "Docs rules" not in block


def test_s4_3_5_4_none_renders_no_docs_bullet(tmp_path: Path) -> None:
    block = _rendered(_root(tmp_path, profile="none"))[BLOCK_KEY]
    assert "**Docs:**" not in block
    assert "Docs rules" not in block
    assert "docs:build" not in block


@pytest.mark.parametrize("archetype", ARCHETYPES)
def test_s4_3_5_5_docs_structure_passes_with_no_hand_written_claude_md(
    tmp_path: Path, archetype: str
) -> None:
    root = _new(tmp_path, archetype)
    assert [f.code for f in DOCS.checks(KilnConfig.load(root), root)] == []


def test_s4_3_5_6_root_hygiene_warns_on_notes_md(repo) -> None:
    from rn_forge.kiln import checks

    root = repo(**{"NOTES.md": "# Notes\n", "README.md": "# r\n"})
    findings = checks.run(root, only="root-hygiene")
    assert [(f.code, f.path) for f in findings] == [
        ("hygiene.stray-root-file", "NOTES.md")
    ]
