"""S11.3.1 — `kiln generate package <name>` for `python-lib`.

Every repository here comes from `kiln new` run beneath `tmp_path`, which runs
`uv init` for real, as `tests/modules/python/test_scaffold.py` does; the
golden-equality repository is built once for the module. A fresh repository's
`uv sync && task validate` and `kiln doctor` need the network and minutes, so
they are not here: the feature's acceptance block runs them.
"""

from __future__ import annotations

import json
import re
import shutil
import subprocess
import tomllib
from collections.abc import Iterator
from contextlib import contextmanager
from pathlib import Path
from typing import Any

import pytest
from rn_forge.commons.exceptions import AppException
from rn_forge.commons.runtime.console import OutputMode, console

from rn_forge.kiln import commands, main
from rn_forge.kiln.config import KilnConfig
from rn_forge.kiln.modules.docs.nav import NAV_BLOCK
from rn_forge.kiln.modules.docs.scaffold import PACKAGE_SEEDS
from rn_forge.kiln.modules.python.scaffold import github_remote

GOLDEN = Path(__file__).resolve().parent / "fixtures" / "golden" / "python-lib"
HTTPS = "https://github.com/rn-forge/golden-lib"
NO_REMOTE = (
    "generate.no-remote: a published package needs the repository's GitHub "
    "remote: git remote add origin https://github.com/<owner>/<repo>"
)


def _new(parent: Path, name: str, archetype: str = "python-lib") -> Path:
    """`kiln new` into `parent/name`, staging beneath *parent*."""
    parent.mkdir(parents=True, exist_ok=True)
    with pytest.MonkeyPatch.context() as patch:
        patch.chdir(parent)
        commands.new(Path(name), archetype=archetype, docs="mkdocs", yes=True)
    return parent / name


def _git(root: Path, *args: str) -> str:
    done = subprocess.run(
        ["git", *args], cwd=root, check=True, capture_output=True, text=True
    )
    return done.stdout


def _lib(parent: Path, remote: str | None, name: str = "golden-lib") -> Path:
    root = _new(parent, name)
    _git(root, "init", "-q")
    if remote is not None:
        _git(root, "remote", "add", "origin", remote)
    return root


def _generate(root: Path, name: str) -> None:
    commands.generate_package(name, path=root)


def _tree(root: Path) -> dict[str, bytes]:
    return {
        path.relative_to(root).as_posix(): path.read_bytes()
        for path in sorted(root.rglob("*"))
        if path.is_file() and ".git" not in path.relative_to(root).parts[:1]
    }


def _toml(path: Path) -> dict[str, Any]:
    return tomllib.loads(path.read_text(encoding="utf-8"))


def _provenance(text: str) -> str:
    return re.sub(r"Generated by kiln \S+ from", "Generated by kiln X from", text)


def _is_subsequence(needle: list[str], haystack: list[str]) -> bool:
    remaining = iter(haystack)
    return all(line in remaining for line in needle)


def _site_description(text: str) -> str:
    return re.sub(
        r"^site_description: .*$", "site_description: X", text, count=1, flags=re.M
    )


@contextmanager
def _refused(code: str) -> Iterator[None]:
    """Expect an `AppException` whose message starts with *code*."""
    with pytest.raises(AppException) as raised:
        yield
    assert raised.value.message.startswith(f"{code}: ")


@pytest.fixture(autouse=True)
def _reset_console_mode() -> Iterator[None]:
    yield
    console.set_mode(OutputMode.PLAIN)


@pytest.fixture(scope="module")
def generated(tmp_path_factory: pytest.TempPathFactory) -> Path:
    """A `golden-lib` repository after `generate package` for both golden packages."""
    root = _lib(tmp_path_factory.mktemp("equality"), HTTPS)
    _generate(root, "golden-alpha")
    _generate(root, "golden-beta")
    return root


def test_s11_3_1_0_the_command_is_declared_as_generate_package() -> None:
    commands_declared = {
        c["name"]: c["target"] for c in main.SURFACE["cli"]["commands"]
    }
    assert commands_declared["generate"] == "rn_forge.kiln.commands:generate_app"
    assert [c.name for c in commands.generate_app.registered_commands] == ["package"]


def test_s11_3_1_1_managed_files_equal_the_golden(generated: Path) -> None:
    state = json.loads(
        (generated / ".rn-forge/kiln/state.json").read_text(encoding="utf-8")
    )["entries"]
    golden_state = json.loads(
        (GOLDEN / ".rn-forge/kiln/state.json").read_text(encoding="utf-8")
    )["entries"]
    managed = [
        path
        for path, entry in state.items()
        if entry["kind"] == "managed" and path in golden_state
    ]
    assert {"tasks/docs.yml", "tasks/quality.yml", "tasks/workspace.yml"} <= set(
        managed
    )
    for path in managed:
        assert _provenance((generated / path).read_text(encoding="utf-8")) == (
            _provenance((GOLDEN / path).read_text(encoding="utf-8"))
        ), path


def test_s11_3_1_1_config_lists_both_packages_as_the_golden_does(
    generated: Path,
) -> None:
    config = KilnConfig.load(generated)
    golden = KilnConfig.load(GOLDEN)
    assert config.packages == golden.packages
    assert config.to_document() == golden.to_document()


def test_s11_3_1_1_config_keeps_its_comments(generated: Path) -> None:
    text = (generated / ".rn-forge/kiln/config.toml").read_text(encoding="utf-8")
    assert text.startswith("# The one hand-authored input kiln reads")


def test_s11_3_1_1_root_mkdocs_body_and_package_nav_equal_the_golden(
    generated: Path,
) -> None:
    ours = (generated / "mkdocs.yml").read_text(encoding="utf-8")
    golden = (GOLDEN / "mkdocs.yml").read_text(encoding="utf-8")
    assert _site_description(NAV_BLOCK.render(ours, "")) == _site_description(
        NAV_BLOCK.render(golden, "")
    )
    nav = NAV_BLOCK.extract(ours)
    assert nav is not None
    assert _is_subsequence(
        [
            "  - Packages:",
            "    - golden-alpha: '!include packages/golden-alpha/mkdocs.yml'",
            "    - golden-beta: '!include packages/golden-beta/mkdocs.yml'",
        ],
        nav.splitlines(),
    )
    assert _is_subsequence(
        nav.splitlines(), (NAV_BLOCK.extract(golden) or "").splitlines()
    )


@pytest.mark.parametrize("package", ["golden-alpha", "golden-beta"])
def test_s11_3_1_1_package_seeds_are_the_golden_s_or_contained_in_it(
    generated: Path, package: str
) -> None:
    """Seeds the golden extended by hand must hold in its lines, in order."""
    unextended = {"mkdocs.yml", "docs/changelog.md", "docs/reference/api.md"}
    for seed in PACKAGE_SEEDS:
        ours = (generated / "packages" / package / seed).read_text(encoding="utf-8")
        golden = (GOLDEN / "packages" / package / seed).read_text(encoding="utf-8")
        if seed in unextended:
            assert _site_description(ours) == _site_description(golden), seed
        assert _is_subsequence(
            _site_description(ours).splitlines(),
            _site_description(golden).splitlines(),
        ), seed


@pytest.mark.parametrize("package", ["golden-alpha", "golden-beta"])
def test_s11_3_1_1_member_pyproject_matches_the_golden_where_the_command_writes(
    generated: Path, package: str
) -> None:
    ours = _toml(generated / "packages" / package / "pyproject.toml")
    golden = _toml(GOLDEN / "packages" / package / "pyproject.toml")
    assert ours["project"]["urls"] == golden["project"]["urls"]
    for key in ("name", "requires-python", "dependencies"):
        assert ours["project"][key] == golden["project"][key], key
    assert (
        ours["build-system"]["build-backend"] == golden["build-system"]["build-backend"]
    )
    assert ours["tool"]["uv"] == golden["tool"]["uv"]
    assert ours["tool"]["pytest"] == golden["tool"]["pytest"]
    for key in ("typeCheckingMode", "venv", "venvPath", "reportMissingTypeStubs"):
        assert ours["tool"]["pyright"][key] == golden["tool"]["pyright"][key], key
    ignores = "tests/*"
    assert sorted(ours["tool"]["ruff"]["lint"]["per-file-ignores"][ignores]) == sorted(
        golden["tool"]["ruff"]["lint"]["per-file-ignores"][ignores]
    )


@pytest.mark.parametrize("package", ["golden-alpha", "golden-beta"])
def test_s11_3_1_1_the_sample_test_equals_the_golden_s(
    generated: Path, package: str
) -> None:
    path = Path("packages") / package / "tests" / "test_package.py"
    assert (generated / path).read_text(encoding="utf-8") == (GOLDEN / path).read_text(
        encoding="utf-8"
    )


def test_s11_3_1_1_root_pyproject_workspace_sources_and_groups_equal_the_golden(
    generated: Path,
) -> None:
    ours = _toml(generated / "pyproject.toml")
    golden = _toml(GOLDEN / "pyproject.toml")
    assert ours["tool"]["uv"]["workspace"] == golden["tool"]["uv"]["workspace"]
    for package in ("golden-alpha", "golden-beta"):
        assert ours["tool"]["uv"]["sources"][package] == {"workspace": True}
        assert golden["tool"]["uv"]["sources"][package] == {"workspace": True}
    groups, golden_groups = ours["dependency-groups"], golden["dependency-groups"]
    assert groups["workspace"] == golden_groups["workspace"]
    assert groups["docs"] == golden_groups["docs"]
    assert groups["dev"][0] == golden_groups["dev"][0] == {"include-group": "workspace"}


def test_s11_3_1_1_the_runbook_is_seeded_equal_to_the_golden_s(generated: Path) -> None:
    path = Path("docs/runbooks/adding-a-package.md")
    assert (generated / path).read_text(encoding="utf-8") == (GOLDEN / path).read_text(
        encoding="utf-8"
    )


def test_s11_3_1_2_a_second_apply_dry_run_changes_nothing(
    generated: Path,
    monkeypatch: pytest.MonkeyPatch,
    capsys: pytest.CaptureFixture[str],
) -> None:
    monkeypatch.chdir(generated)
    capsys.readouterr()
    commands.apply(dry_run=True, json=True)
    rows = json.loads(capsys.readouterr().out.strip().splitlines()[-1])["artifacts"]
    assert rows
    assert all(row["action"] in ("unchanged", "skip") for row in rows)
    assert not [
        row for row in rows if row["kind"] != "seeded" and row["action"] == "skip"
    ]


def test_s11_3_1_2_json_lists_the_paths_written_and_the_apply_result(
    tmp_path: Path, capsys: pytest.CaptureFixture[str]
) -> None:
    root = _lib(tmp_path, HTTPS)
    capsys.readouterr()
    commands.generate_package("alpha", path=root, json=True)
    payload = json.loads(capsys.readouterr().out.strip().splitlines()[-1])
    assert payload["root"] == str(root.resolve())
    assert {
        ".rn-forge/kiln/config.toml",
        "pyproject.toml",
        "packages/alpha/pyproject.toml",
        "packages/alpha/mkdocs.yml",
        "packages/alpha/CHANGELOG.md",
        "packages/alpha/README.md",
    } <= set(payload["written"])
    assert {row["action"] for row in payload["artifacts"]} >= {"update"}


def test_s11_3_1_3_ssh_and_https_remotes_write_the_same_urls(tmp_path: Path) -> None:
    urls: list[dict[str, str]] = []
    for index, remote in enumerate(
        (
            "git@github.com:rn-forge/f11-proof.git",
            "https://github.com/rn-forge/f11-proof",
        )
    ):
        root = _lib(tmp_path / str(index), remote, name="f11-proof")
        _generate(root, "alpha")
        urls.append(_toml(root / "packages/alpha/pyproject.toml")["project"]["urls"])
    assert (
        urls[0]
        == urls[1]
        == {
            "Documentation": "https://rn-forge.github.io/f11-proof/packages/alpha/latest/",
            "Source": "https://github.com/rn-forge/f11-proof",
            "Changelog": "https://github.com/rn-forge/f11-proof/blob/main/packages/alpha/CHANGELOG.md",
            "Issues": "https://github.com/rn-forge/f11-proof/issues",
        }
    )


@pytest.mark.parametrize(
    ("url", "expected"),
    [
        ("https://github.com/o/r", "https://github.com/o/r"),
        ("https://github.com/o/r.git", "https://github.com/o/r"),
        ("git@github.com:o/r", "https://github.com/o/r"),
        ("git@github.com:o/r.git", "https://github.com/o/r"),
        ("https://gitlab.com/o/r", None),
        ("git@gitlab.com:o/r.git", None),
        ("../local", None),
    ],
)
def test_s11_3_1_3_github_remote_accepts_https_and_ssh_only(
    tmp_path: Path, url: str, expected: str | None
) -> None:
    _git(tmp_path, "init", "-q")
    _git(tmp_path, "remote", "add", "origin", url)
    assert github_remote(tmp_path) == expected


def test_s11_3_1_4_no_origin_fails_with_no_remote_and_writes_nothing(
    tmp_path: Path,
) -> None:
    root = _lib(tmp_path, None)
    before = _git(root, "status", "--porcelain")
    tree = _tree(root)
    with pytest.raises(AppException) as raised:
        _generate(root, "alpha")
    assert raised.value.message == NO_REMOTE
    assert _git(root, "status", "--porcelain") == before
    assert _tree(root) == tree


def test_s11_3_1_4_a_non_github_origin_fails_with_no_remote(tmp_path: Path) -> None:
    root = _lib(tmp_path, "https://gitlab.com/rn-forge/golden-lib")
    tree = _tree(root)
    with _refused("generate.no-remote"):
        _generate(root, "alpha")
    assert _tree(root) == tree


def test_s11_3_1_5_a_repeated_name_fails_with_package_exists_and_writes_nothing(
    generated: Path, tmp_path: Path
) -> None:
    root = tmp_path / "copy"
    shutil.copytree(generated, root, symlinks=True)
    tree = _tree(root)
    with _refused("generate.package-exists"):
        _generate(root, "golden-alpha")
    assert _tree(root) == tree


def test_s11_3_1_5_an_existing_directory_fails_with_package_exists(
    generated: Path, tmp_path: Path
) -> None:
    root = tmp_path / "copy"
    shutil.copytree(generated, root, symlinks=True)
    (root / "packages" / "stray").mkdir()
    tree = _tree(root)
    with _refused("generate.package-exists"):
        _generate(root, "stray")
    assert _tree(root) == tree


@pytest.mark.parametrize("name", ["Alpha", "a_b", "-a", "a-", "a--b", "1a", "a b"])
def test_s11_3_1_5_a_name_that_is_not_kebab_case_fails_with_invalid_name(
    generated: Path, tmp_path: Path, name: str
) -> None:
    root = tmp_path / "copy"
    shutil.copytree(generated, root, symlinks=True)
    tree = _tree(root)
    with _refused("generate.invalid-name"):
        _generate(root, name)
    assert _tree(root) == tree


def test_s11_3_1_5_a_python_app_fails_with_unsupported_archetype_and_writes_nothing(
    tmp_path: Path,
) -> None:
    root = _new(tmp_path, "app", archetype="python-app")
    tree = _tree(root)
    with _refused("generate.unsupported-archetype"):
        _generate(root, "alpha")
    assert _tree(root) == tree
    assert not (root / "packages").exists()
