# Generated by kiln golden from .rn-forge/kiln/config.toml — do not edit; run 'kiln apply'
"""Validate the built site's graph: broken relative links, broken heading anchors,
nav entries pointing at nothing, and pages unreachable from the nav.

`mkdocs.yml`'s `nav` is the single source of page structure, so a page nobody
navigates to and nobody links to is a page nobody reads. Generated-and-gitignored
subtrees under `docs/` (mkdocstrings or TypeDoc output) are detected from
`.gitignore` and skipped — they do not exist until the generators run.

Usage: check_docs.py [repo-root]   (default: current directory)
"""

from __future__ import annotations

import sys
from pathlib import Path
from typing import Any

from _common import headings, is_external, links, load_yaml


def generated_prefixes(root: Path, docs_dir: Path) -> list[Path]:
    """Directories under docs/ that are gitignored — generator output, not prose."""
    gitignore = root / ".gitignore"
    if not gitignore.exists():
        return []
    prefixes: list[Path] = []
    for raw in gitignore.read_text(encoding="utf-8").splitlines():
        line = raw.strip()
        if not line or line.startswith("#"):
            continue
        candidate = (root / line.rstrip("/")).resolve()
        if candidate == docs_dir or docs_dir in candidate.parents:
            prefixes.append(candidate)
    return prefixes


class Site:
    def __init__(self, root: Path) -> None:
        self.root = root
        self.docs_dir = root / "docs"
        self.mkdocs_yml = root / "mkdocs.yml"
        self.generated = generated_prefixes(root, self.docs_dir)

    def is_generated(self, path: Path) -> bool:
        return any(path == p or p in path.parents for p in self.generated)

    def markdown_files(self) -> list[Path]:
        return sorted(
            path
            for path in self.docs_dir.rglob("*.md")
            if not self.is_generated(path) and not path.name.startswith("_")
        )

    def nav_paths(self) -> list[str]:
        config = load_yaml(self.mkdocs_yml)
        paths: list[str] = []

        def walk(node: Any) -> None:
            if isinstance(node, str):
                if node.endswith(".md"):
                    paths.append(node)
            elif isinstance(node, dict):
                for value in node.values():
                    walk(value)
            elif isinstance(node, list):
                for item in node:
                    walk(item)

        walk(config.get("nav", []))
        return paths

    def anchors_in(self, path: Path) -> set[str]:
        if not path.exists():
            return set()
        return headings(path.read_text(encoding="utf-8"))

    def linked_pages(self, path: Path) -> set[Path]:
        targets: set[Path] = set()
        for link in links(path.read_text(encoding="utf-8")):
            if is_external(link):
                continue
            target, _, _anchor = link.partition("#")
            if not target.endswith(".md"):
                continue
            resolved = (path.parent / target).resolve()
            if resolved.exists():
                targets.add(resolved)
        return targets

    def check_nav_targets_exist(self) -> list[str]:
        errors: list[str] = []
        for nav_path in self.nav_paths():
            target = (self.docs_dir / nav_path).resolve()
            if self.is_generated(target) or target.exists():
                continue
            errors.append(f"mkdocs.yml nav references missing page: {nav_path!r}")
        return errors

    def check_orphans(self) -> list[str]:
        """A page is reachable if the nav names it, or a reachable page links to it."""
        frontier = [
            (self.docs_dir / nav_path).resolve()
            for nav_path in self.nav_paths()
            if (self.docs_dir / nav_path).resolve().exists()
        ]
        reachable = set(frontier)
        while frontier:
            for linked in self.linked_pages(frontier.pop()):
                if linked not in reachable:
                    reachable.add(linked)
                    frontier.append(linked)

        return [
            f"orphan page not reachable from mkdocs.yml nav: {path.relative_to(self.root)}"
            for path in self.markdown_files()
            if path.resolve() not in reachable
        ]

    def check_links(self) -> list[str]:
        errors: list[str] = []
        for path in self.markdown_files():
            for link in links(path.read_text(encoding="utf-8")):
                if is_external(link):
                    continue
                target, _, anchor = link.partition("#")
                resolved = path if not target else (path.parent / target).resolve()
                if resolved.suffix and resolved.suffix != ".md":
                    continue  # a non-Markdown asset is not this check's job
                rel = path.relative_to(self.root)
                if not resolved.exists():
                    if not self.is_generated(resolved):
                        errors.append(f"{rel}: broken link to {link!r}")
                    continue
                if (
                    anchor
                    and not self.is_generated(resolved)
                    and anchor not in self.anchors_in(resolved)
                ):
                    errors.append(f"{rel}: broken anchor in {link!r}")
        return errors


def main() -> int:
    root = Path(sys.argv[1] if len(sys.argv) > 1 else ".").resolve()
    site = Site(root)
    errors = site.check_nav_targets_exist() + site.check_orphans() + site.check_links()
    if errors:
        for error in errors:
            print(error)
        print(f"\n{len(errors)} docs check failure(s)")
        return 1
    print("docs check passed")
    return 0


if __name__ == "__main__":
    sys.exit(main())
