# Generated by kiln golden from .rn-forge/kiln/config.toml — do not edit; run 'kiln apply'
"""Shared helpers for the docs scripts: the area model, findings, and the small
amount of Markdown parsing the three checkers agree on.

Standard library only, apart from an optional `pyyaml` import with a fallback
loader for the flat YAML subset `_areas.yml` uses. The docs scripts run in
repos whose docs dependency group may not be synced yet — `task docs:nav` in
particular is wired into `task lint`, which a developer runs before installing
the docs extras.

The area *keys* are deliberately not a fixed list. `docs/_areas.yml` is seeded
by kiln and then owned by the repo, so a repo can add an area kiln has never
heard of (kiln ADR-0005) and these scripts validate the tree against whatever
the repo declares.
"""

from __future__ import annotations

import re
from dataclasses import dataclass
from pathlib import Path
from typing import Any

try:
    import yaml as _yaml
except ImportError:  # pragma: no cover - exercised in repos without pyyaml
    _yaml = None

NAV_VALUES = {"children", "index-only"}


@dataclass(frozen=True)
class Area:
    key: str
    title: str
    nav: str
    optional: bool = False
    generated: bool = False


@dataclass(frozen=True)
class Finding:
    path: str
    rule: str
    message: str

    def to_dict(self) -> dict[str, str]:
        return {"path": self.path, "rule": self.rule, "message": self.message}


def _yaml_scalar(value: str) -> Any:
    if value == "":
        return None
    if value in ("true", "True"):
        return True
    if value in ("false", "False"):
        return False
    if value.startswith('"') and value.endswith('"'):
        return value[1:-1]
    if value.startswith("'") and value.endswith("'"):
        return value[1:-1]
    if re.fullmatch(r"-?\d+", value):
        return int(value)
    return value


def _yaml_fallback_load(text: str) -> dict[str, Any]:
    """A loader for the flat YAML subset `_areas.yml` uses: a top-level mapping
    with scalar values and one list-of-mappings value, two levels of
    indentation, no anchors, no flow style, no multiline scalars."""
    root: dict[str, Any] = {}
    current_list_key: str | None = None
    current_item: dict[str, Any] | None = None
    for raw_line in text.splitlines():
        line = raw_line.split(" #", 1)[0].rstrip()
        if not line.strip() or line.strip().startswith("#"):
            continue
        indent = len(line) - len(line.lstrip(" "))
        stripped = line.strip()
        if indent == 0:
            if stripped.endswith(":"):
                current_list_key = stripped[:-1]
                root[current_list_key] = []
                current_item = None
            else:
                key, _, value = stripped.partition(":")
                root[key.strip()] = _yaml_scalar(value.strip())
                current_list_key = None
                current_item = None
            continue
        if stripped.startswith("- "):
            if current_list_key is None:
                continue
            current_item = {}
            root[current_list_key].append(current_item)
            key, _, value = stripped[2:].partition(":")
            current_item[key.strip()] = _yaml_scalar(value.strip())
            continue
        if current_item is not None:
            key, _, value = stripped.partition(":")
            current_item[key.strip()] = _yaml_scalar(value.strip())
    return root


def load_yaml(path: Path) -> Any:
    text = path.read_text(encoding="utf-8")
    if _yaml is not None:
        return _yaml.safe_load(text)
    return _yaml_fallback_load(text)


def load_areas(docs_root: Path) -> list[Area]:
    """Load `docs/_areas.yml`. A missing manifest is the caller's finding to
    report, not something to paper over with a default."""
    manifest_path = docs_root / "_areas.yml"
    if not manifest_path.exists():
        raise FileNotFoundError(f"{manifest_path} does not exist")
    raw = load_yaml(manifest_path)
    areas: list[Area] = []
    for entry in raw.get("areas", []):
        key = str(entry["key"])
        nav = str(entry.get("nav", "children"))
        if nav not in NAV_VALUES:
            raise ValueError(f"invalid nav value for area {key!r}: {nav!r}")
        areas.append(
            Area(
                key=key,
                title=str(entry.get("title", key.title())),
                nav=nav,
                optional=bool(entry.get("optional", False)),
                generated=bool(entry.get("generated", False)),
            )
        )
    return areas


LINK_RE = re.compile(r"\[[^\]]*\]\(([^)\s]+)\)")
HEADING_RE = re.compile(r"^(#{1,6})[ \t]+(.+)$")
FENCED_CODE_RE = re.compile(r"```.*?```", re.DOTALL)

_SLUGIFY_STRIP_RE = re.compile(r"[^\w\s-]", re.UNICODE)
_SLUGIFY_HYPHENATE_RE = re.compile(r"[-\s]+")


def strip_fenced_code(text: str) -> str:
    return FENCED_CODE_RE.sub("", text)


def slugify(heading_text: str) -> str:
    """Match MkDocs/python-markdown's `toc` slugifier closely enough for
    anchor-link checking: lowercase, drop punctuation other than word
    characters, hyphens and whitespace, collapse the rest to a single `-`."""
    text = heading_text.strip().lower()
    text = _SLUGIFY_STRIP_RE.sub("", text)
    text = _SLUGIFY_HYPHENATE_RE.sub("-", text)
    return text.strip("-")


def headings(text: str) -> set[str]:
    return {
        slugify(match.group(2).strip())
        for line in text.splitlines()
        if (match := HEADING_RE.match(line))
    }


def links(text: str) -> list[str]:
    return [match.group(1) for match in LINK_RE.finditer(strip_fenced_code(text))]


def is_external(link: str) -> bool:
    return link.startswith(("http://", "https://", "mailto:"))
