# Generated by kiln golden from .rn-forge/kiln/config.toml — do not edit; run 'kiln apply'
"""Fail if the task vocabulary's wrapper/inner split or the validate gate has shrunk.

Three rules:

1. The root `Taskfile.yml` holds wrappers only. Every `cmds:` entry in it must
   be a `task:` call into a namespace file, never raw shell. Anything that
   shells out to a real tool belongs in the namespace file that owns it.
2. Every task, in the root file and in every `tasks/*.yml`, carries a non-empty
   `desc:`. That is what keeps `task --list` self-documenting, which is the
   whole reason the vocabulary is easier to remember than the tools underneath.
3. Every task named in REQUIRED_VALIDATE is reachable from `validate`. This is
   the CI half of the `gate.shrunk` rule: a repo cannot quietly drop a gate
   from its aggregate by editing a wrapper.

Usage: check_task_layout.py [repo-root]   (default: current directory)
"""

from __future__ import annotations

import sys
from pathlib import Path

import yaml

# BEGIN kiln config
REQUIRED_VALIDATE = [
    "quality:lint:python",
    "quality:lint:generated",
    "quality:lint:rn-forge-deps",
    "quality:lint:imports",
    "quality:lint:task-layout",
    "quality:lint:ci-entrypoint",
    "quality:lint:docs",
    "quality:lint:docs-structure",
    "quality:lint:docs-nav",
    "quality:typecheck:python",
    "quality:test:python",
    "docs:build",
]
# END kiln config


def task_specs(document: object) -> dict[str, object]:
    """The `tasks:` mapping of a Taskfile, or empty if there isn't one."""
    if not isinstance(document, dict):
        return {}
    tasks = document.get("tasks")
    return tasks if isinstance(tasks, dict) else {}


def check_desc(path: Path, name: str, spec: object) -> list[str]:
    if isinstance(spec, dict) and str(spec.get("desc", "")).strip():
        return []
    return [f"{path}: task `{name}` has no non-empty `desc:`"]


def check_wrapper_only(path: Path, name: str, spec: object) -> list[str]:
    """Every cmds entry in the root file must be a `task:` call."""
    # `name: echo hi` and `name: [a, b]` are go-task shorthand for raw shell.
    if isinstance(spec, (str, list)):
        return [
            (
                f"{path}: task `{name}` is shorthand for a raw shell command — "
                f"the root file holds wrappers only"
            )
        ]
    if not isinstance(spec, dict):
        return []

    errors: list[str] = []
    cmds = spec.get("cmds")
    if cmds is None:
        return errors
    if not isinstance(cmds, list):
        cmds = [cmds]

    for index, entry in enumerate(cmds):
        if isinstance(entry, dict) and "task" in entry:
            continue
        shown = entry if isinstance(entry, str) else type(entry).__name__
        errors.append(
            f"{path}: task `{name}` cmds[{index}] is not a `task:` call ({shown!r}) — "
            f"move the command into the namespace file that owns it and call it from here"
        )
    return errors


def task_refs(spec: object) -> list[str]:
    """The `task:` targets a task calls, in order."""
    if not isinstance(spec, dict):
        return []
    cmds = spec.get("cmds")
    if cmds is None:
        return []
    if not isinstance(cmds, list):
        cmds = [cmds]
    refs: list[str] = []
    for entry in cmds:
        if isinstance(entry, dict) and isinstance(entry.get("task"), str):
            refs.append(entry["task"])
    return refs


def load_graph(root: Path) -> tuple[dict[str, object], set[str]]:
    """Every task in the repo keyed by its fully qualified name, and the
    namespaces `tasks/*.yml` contributes."""
    graph: dict[str, object] = {}

    root_taskfile = root / "Taskfile.yml"
    for name, spec in task_specs(yaml.safe_load(root_taskfile.read_text())).items():
        graph[name] = spec

    namespaces: set[str] = set()
    for namespace_file in sorted((root / "tasks").glob("*.yml")):
        namespace = namespace_file.stem
        namespaces.add(namespace)
        for name, spec in task_specs(
            yaml.safe_load(namespace_file.read_text())
        ).items():
            graph[f"{namespace}:{name}"] = spec

    return graph, namespaces


def resolve(ref: str, namespace: str | None, graph: dict[str, object]) -> str:
    """Normalise a `task:` reference to a fully qualified name.

    A leading `:` is go-task's "from the root Taskfile" prefix. Inside a
    namespace file an unprefixed reference means a sibling task first, and only
    then a root-level one.
    """
    if ref.startswith(":"):
        return ref[1:]
    if namespace is not None and f"{namespace}:{ref}" in graph:
        return f"{namespace}:{ref}"
    return ref


def reachable_from(
    entrypoint: str, graph: dict[str, object], namespaces: set[str]
) -> set[str]:
    seen: set[str] = set()
    frontier = [entrypoint]
    while frontier:
        current = frontier.pop()
        if current in seen:
            continue
        seen.add(current)
        prefix = current.split(":", 1)[0]
        namespace = prefix if prefix in namespaces else None
        for ref in task_refs(graph.get(current)):
            frontier.append(resolve(ref, namespace, graph))
    return seen


def check_gate(graph: dict[str, object], namespaces: set[str]) -> list[str]:
    if "validate" not in graph:
        return ["Taskfile.yml: no `validate` task — the aggregate gate is missing"]
    reachable = reachable_from("validate", graph, namespaces)
    return [
        f"Taskfile.yml: `{required}` is not reachable from `validate` — the gate has shrunk"
        for required in REQUIRED_VALIDATE
        if required not in reachable
    ]


def main() -> int:
    root = Path(sys.argv[1] if len(sys.argv) > 1 else ".").resolve()
    root_taskfile = root / "Taskfile.yml"

    if not root_taskfile.exists():
        print(f"{root_taskfile}: not found")
        return 1

    errors: list[str] = []

    document = yaml.safe_load(root_taskfile.read_text())
    for name, spec in task_specs(document).items():
        rel = root_taskfile.relative_to(root)
        errors.extend(check_desc(rel, name, spec))
        errors.extend(check_wrapper_only(rel, name, spec))

    for namespace_file in sorted((root / "tasks").glob("*.yml")):
        rel = namespace_file.relative_to(root)
        for name, spec in task_specs(
            yaml.safe_load(namespace_file.read_text())
        ).items():
            errors.extend(check_desc(rel, name, spec))

    graph, namespaces = load_graph(root)
    errors.extend(check_gate(graph, namespaces))

    if errors:
        for error in errors:
            print(error)
        return 1

    return 0


if __name__ == "__main__":
    sys.exit(main())
