"""S4.3.2 — the `docs` module's artifacts: the seeded tree.

Also proves the five properties every F4.3 story owes its module
(`docs/specs/epics/E4-generator/F4.3-concern-modules.md`).
"""

from __future__ import annotations

import re
from pathlib import Path

import pytest
from rn_forge.tooling.generation import Action, ArtifactKind

from rn_forge.kiln.config import KilnConfig
from rn_forge.kiln.modules.core import cycle
from rn_forge.kiln.modules.docs import DOCS, generate
from rn_forge.kiln.modules.docs.artifacts import SEEDS
from rn_forge.kiln.modules.docs.nav import NAV_BLOCK, build_nav
from rn_forge.kiln.modules.docs.scaffold import scaffold
from rn_forge.kiln.modules.instructions.scaffold import (
    scaffold as instructions_scaffold,
)

GOLDEN = Path(__file__).resolve().parents[2] / "fixtures" / "golden"
ARCHETYPES = ("python-app", "python-tool", "python-lib")

CONFIG = """
schema_version = 1

[repository]
name = "demo"
archetype = "{archetype}"

[docs]
profile = "{profile}"
"""

PACKAGES = """
[archetype."python-lib"]
packages = ["packages/alpha", "packages/beta"]
"""

GROWN = {
    "docs/index.md",
    "docs/architecture/index.md",
    "docs/guides/index.md",
    "docs/runbooks/index.md",
    "docs/adr/index.md",
}
"""Seeded pages the goldens have since added their own entries to."""


def _seeds(archetype: str) -> tuple[str, ...]:
    """The seeds *archetype* carries.

    `python-lib` has no `docs/reference/`; only it has the adding-a-package runbook.
    """
    if archetype == "python-lib":
        return tuple(p for p in SEEDS if not p.startswith("docs/reference/"))
    return tuple(p for p in SEEDS if p != "docs/runbooks/adding-a-package.md")


def _kind(path: str) -> ArtifactKind:
    managed = path.endswith("/_structure.md")
    return ArtifactKind.MANAGED if managed else ArtifactKind.SEEDED


def _root(
    tmp_path: Path, archetype: str = "python-tool", profile: str = "mkdocs"
) -> Path:
    config = tmp_path / ".rn-forge" / "kiln" / "config.toml"
    config.parent.mkdir(parents=True)
    text = CONFIG.format(archetype=archetype, profile=profile)
    if archetype == "python-lib":
        text += PACKAGES
    config.write_text(text, encoding="utf-8")
    return tmp_path


def _new(tmp_path: Path, archetype: str = "python-tool") -> Path:
    """Scaffold and apply into an empty directory, as `kiln new` will."""
    root = _root(tmp_path, archetype)
    config = KilnConfig.load(root)
    scaffold(root, config)
    instructions_scaffold(root, config)
    cycle.apply(root, home=tmp_path / "home")
    generate.generate(root)
    return root


def _actions(root: Path, tmp_path: Path) -> dict[str, Action]:
    return {
        change.key: change.action
        for change in cycle.plan(root, home=tmp_path / "home").changes
    }


def _codes(root: Path) -> list[str]:
    return sorted(f.code for f in DOCS.checks(KilnConfig.load(root), root))


@pytest.mark.parametrize("archetype", ARCHETYPES)
def test_s4_3_2_property1_renders_exactly_the_module_s_template_inventory_row(
    tmp_path: Path, archetype: str
) -> None:
    root = _root(tmp_path, archetype)
    artifacts = DOCS.artifacts(KilnConfig.load(root), root)
    assert [(a.key, a.kind) for a in artifacts] == [
        *((path, _kind(path)) for path in _seeds(archetype)),
    ]


@pytest.mark.parametrize("archetype", ARCHETYPES)
def test_s4_3_2_property2_into_an_empty_directory_only_creates(
    tmp_path: Path, archetype: str
) -> None:
    actions = _actions(_root(tmp_path, archetype), tmp_path)
    assert set(actions.values()) <= {Action.CREATE, Action.INSERT, Action.SKIP}
    assert all(
        actions[path] is Action.CREATE for path in _seeds(archetype)
    )  # managed too


@pytest.mark.parametrize("archetype", ARCHETYPES)
def test_s4_3_2_property3_a_second_apply_changes_nothing(
    tmp_path: Path, archetype: str
) -> None:
    """Seeds report `SKIP` once present — the engine never inspects them."""
    root = _new(tmp_path, archetype)
    actions = _actions(root, tmp_path)
    expected = {
        path: Action.UNCHANGED if _kind(path) is ArtifactKind.MANAGED else Action.SKIP
        for path in _seeds(archetype)
    }
    assert {path: actions[path] for path in _seeds(archetype)} == expected
    assert {a for k, a in actions.items() if k not in SEEDS} <= {
        Action.UNCHANGED,
        Action.SKIP,
    }


def _normalized(text: str) -> str:
    """Drop the two identity lines a repo writes for itself."""
    text = re.sub(r"^site_name: .*$", "site_name: X", text, count=1, flags=re.M)
    return re.sub(
        r"^site_description: .*$", "site_description: X", text, count=1, flags=re.M
    )


def _provenance(text: str) -> str:
    """Drop the provenance line's kiln version, the only line that never matches."""
    return re.sub(
        r"^<!-- Generated by kiln .*? from",
        "<!-- Generated by kiln X from",
        text,
        count=1,
        flags=re.M,
    )


def _is_subsequence(needle: list[str], haystack: list[str]) -> bool:
    remaining = iter(haystack)
    return all(line in remaining for line in needle)


@pytest.mark.parametrize("archetype", ARCHETYPES)
def test_s4_3_2_property4_matches_its_golden(tmp_path: Path, archetype: str) -> None:
    """Grown index pages must still contain every seeded line, in order."""
    golden = GOLDEN / archetype
    config = KilnConfig.load(golden)
    rendered = {a.key: a.content for a in DOCS.artifacts(config, golden)}

    mkdocs = (golden / "mkdocs.yml").read_text(encoding="utf-8")
    nav = build_nav(golden / "docs", config.packages)
    assert NAV_BLOCK.extract(mkdocs) == nav
    scaffold(tmp_path, config)
    body = (tmp_path / "mkdocs.yml").read_text(encoding="utf-8")
    assert NAV_BLOCK.extract(body) == ""
    assert _normalized(NAV_BLOCK.render(body, nav)) == (_normalized(mkdocs))

    for path in _seeds(archetype):
        on_disk = (golden / path).read_text(encoding="utf-8")
        if path in GROWN:
            assert _is_subsequence(rendered[path].splitlines(), on_disk.splitlines()), (
                path
            )
        else:
            assert _provenance(rendered[path]) == _provenance(on_disk), path


def test_s4_3_2_property5_checks_pass_on_the_rendered_output(tmp_path: Path) -> None:
    assert _codes(_new(tmp_path)) == []


def test_s4_3_2_property5_structure_fails_on_a_missing_area(tmp_path: Path) -> None:
    root = _new(tmp_path)
    for page in (root / "docs" / "guides").iterdir():
        page.unlink()
    (root / "docs" / "guides").rmdir()
    assert "docs.missing-area" in _codes(root)


def test_s4_3_2_property5_nav_fails_on_an_unnavigated_page(tmp_path: Path) -> None:
    root = _new(tmp_path)
    (root / "docs" / "guides" / "setup.md").write_text("# Setup\n", encoding="utf-8")
    assert "docs.nav-stale" in _codes(root)


def test_s4_3_2_property5_site_fails_on_a_broken_link(tmp_path: Path) -> None:
    root = _new(tmp_path)
    (root / "docs" / "guides" / "index.md").write_text(
        "# Guides\n\n- [Gone](gone.md)\n", encoding="utf-8"
    )
    assert "docs.broken-link" in _codes(root)


@pytest.mark.parametrize("profile", ["none", "external"])
def test_s4_3_2_1_non_mkdocs_profiles_render_no_docs_artifacts(
    tmp_path: Path, profile: str
) -> None:
    root = _root(tmp_path, profile=profile)
    config = KilnConfig.load(root)
    assert DOCS.artifacts(config, root) == []
    scaffold(root, config)
    assert not (root / "mkdocs.yml").exists()


@pytest.mark.parametrize("archetype", ARCHETYPES)
def test_s4_3_2_1_mkdocs_build_strict_passes_on_the_rendered_tree(
    tmp_path: Path, archetype: str
) -> None:
    from mkdocs.commands.build import build
    from mkdocs.config import load_config

    root = _new(tmp_path / "repo", archetype)
    if archetype == "python-lib":
        # The `monorepo` plugin is a docs-group dependency of the generated
        # repo, not of kiln; its own gate builds the real site.
        mkdocs = root / "mkdocs.yml"
        mkdocs.write_text(
            mkdocs.read_text(encoding="utf-8").replace("  - monorepo\n", ""),
            encoding="utf-8",
        )
    build(
        load_config(
            str(root / "mkdocs.yml"), strict=True, site_dir=str(tmp_path / "site")
        )
    )
    assert (tmp_path / "site" / "index.html").is_file()


def test_s4_3_2_2_an_edited_areas_yml_survives_and_is_what_the_check_reads(
    tmp_path: Path,
) -> None:
    root = _new(tmp_path)
    areas = root / "docs" / "_areas.yml"
    edited = areas.read_text(encoding="utf-8") + "  - key: notes\n    title: Notes\n"
    areas.write_text(edited, encoding="utf-8")

    assert _actions(root, tmp_path)["docs/_areas.yml"] is Action.SKIP
    cycle.apply(root, home=tmp_path / "home")
    assert areas.read_text(encoding="utf-8") == edited
    findings = DOCS.checks(KilnConfig.load(root), root)
    assert any(
        f.code == "docs.missing-area" and Path(f.path or "").name == "notes"
        for f in findings
    )


def test_s4_3_2_3_a_new_page_updates_only_the_nav_block(tmp_path: Path) -> None:
    root = _new(tmp_path)
    mkdocs = root / "mkdocs.yml"
    before = mkdocs.read_text(encoding="utf-8")
    (root / "docs" / "guides" / "setup.md").write_text("# Setup\n", encoding="utf-8")

    assert {
        k
        for k, a in _actions(root, tmp_path).items()
        if a not in (Action.UNCHANGED, Action.SKIP)
    } == set()

    assert generate.generate(root) == ([mkdocs], [])
    after = mkdocs.read_text(encoding="utf-8")
    assert "guides/setup.md" in (NAV_BLOCK.extract(after) or "")
    assert NAV_BLOCK.remove(after) == NAV_BLOCK.remove(before)
    assert _codes(root) == []


@pytest.mark.parametrize("archetype", ARCHETYPES)
def test_s13_1_1_2_no_docs_artifact_is_a_block(tmp_path: Path, archetype: str) -> None:
    root = _root(tmp_path, archetype)
    kinds = {a.kind for a in DOCS.artifacts(KilnConfig.load(root), root)}
    assert ArtifactKind.BLOCK not in kinds


@pytest.mark.parametrize("archetype", ARCHETYPES)
def test_s11_4_2_structure_files_are_managed_and_indexes_and_areas_are_seeded(
    tmp_path: Path, archetype: str
) -> None:
    root = _root(tmp_path, archetype)
    kinds = {a.key: a.kind for a in DOCS.artifacts(KilnConfig.load(root), root)}
    seeds = _seeds(archetype)
    structures = [path for path in seeds if path.endswith("/_structure.md")]
    assert len(structures) == (7 if archetype == "python-lib" else 8)
    assert all(kinds[path] is ArtifactKind.MANAGED for path in structures)
    others = [path for path in seeds if path not in structures]
    assert "docs/_areas.yml" in others
    assert all(kinds[path] is ArtifactKind.SEEDED for path in others)


@pytest.mark.parametrize("archetype", ARCHETYPES)
def test_s11_4_2_structure_files_carry_kiln_s_provenance_header(
    tmp_path: Path, archetype: str
) -> None:
    root = _root(tmp_path, archetype)
    for artifact in DOCS.artifacts(KilnConfig.load(root), root):
        first = artifact.content.splitlines()[0]
        if artifact.kind is ArtifactKind.MANAGED:
            assert re.fullmatch(
                r"<!-- Generated by kiln \S+ from \.rn-forge/kiln/config\.toml"
                r" — do not edit; run 'kiln apply' -->",
                first,
            ), artifact.key
        else:
            assert "Generated by kiln" not in first, artifact.key


def test_s11_4_2_an_edited_structure_file_is_drift_and_an_edited_index_is_not(
    tmp_path: Path,
) -> None:
    root = _new(tmp_path)
    structure = root / "docs" / "specs" / "_structure.md"
    index = root / "docs" / "specs" / "index.md"
    original = structure.read_text(encoding="utf-8")
    structure.write_text(original.replace("belongs", "belonged", 1), encoding="utf-8")
    index.write_text(index.read_text(encoding="utf-8") + "\nNote.\n", encoding="utf-8")

    actions = _actions(root, tmp_path)
    assert actions["docs/specs/_structure.md"] is Action.DRIFT
    assert actions["docs/specs/index.md"] is Action.SKIP


def _config_root(tmp_path: Path, archetype: str, extra: str = "") -> Path:
    config = tmp_path / ".rn-forge" / "kiln" / "config.toml"
    config.parent.mkdir(parents=True)
    text = CONFIG.format(archetype=archetype, profile="mkdocs") + extra
    config.write_text(text, encoding="utf-8")
    return tmp_path


def _rendered_mkdocs(root: Path) -> str:
    scaffold(root, KilnConfig.load(root))
    return (root / "mkdocs.yml").read_text(encoding="utf-8")


@pytest.mark.parametrize("archetype", ARCHETYPES)
def test_s11_2_2_1_the_docs_artifacts_reproduce_the_golden_for_both_packages(
    tmp_path: Path, archetype: str
) -> None:
    """Acceptance 1: the F4.3 property tests above run against each golden's
    `config.toml`, and the `python-lib` one lists `golden-alpha` and
    `golden-beta`; this pins that fact."""
    config = KilnConfig.load(GOLDEN / archetype)
    assert config.packages == (
        ("packages/golden-alpha", "packages/golden-beta")
        if archetype == "python-lib"
        else ()
    )


def test_s11_2_2_2_a_python_lib_root_body_has_monorepo_glob_paths_and_snippets(
    tmp_path: Path,
) -> None:
    body = _rendered_mkdocs(_config_root(tmp_path, "python-lib"))
    assert "  - search\n  - monorepo\n  - mkdocstrings:" in body
    assert "paths: [packages/*/src]" in body
    assert "  - pymdownx.snippets:\n      check_paths: true\n" in body


@pytest.mark.parametrize(
    ("archetype", "extra", "paths"),
    [
        ("python-app", "", "[src]"),
        ("python-tool", "", "[src]"),
        (
            "python-app",
            '\n[archetype."python-app"]\npackages = ["packages/core"]\n',
            "[src, packages/core/src]",
        ),
    ],
)
def test_s11_2_2_3_other_archetypes_list_src_and_each_package_src(
    tmp_path: Path, archetype: str, extra: str, paths: str
) -> None:
    body = _rendered_mkdocs(_config_root(tmp_path, archetype, extra))
    assert f"paths: {paths}\n" in body
    assert "monorepo" not in body
    assert "snippets" not in body


def test_s11_2_2_4_python_lib_adds_the_packages_area_and_the_package_docs_section(
    tmp_path: Path,
) -> None:
    def rendered(archetype: str) -> dict[str, str]:
        root = _config_root(tmp_path / archetype, archetype)
        return {a.key: a.content for a in DOCS.artifacts(KilnConfig.load(root), root)}

    lib, tool = rendered("python-lib"), rendered("python-tool")
    assert (
        "  - key: packages\n    title: Packages\n    nav: include\n"
        in (lib["docs/_areas.yml"])
    )
    assert "## Package docs" in lib["docs/_structure.md"]
    assert "packages" not in tool["docs/_areas.yml"]
    assert "## Package docs" not in tool["docs/_structure.md"]


def test_s11_2_2_5_python_lib_seeds_no_reference_area_and_the_others_keep_it(
    tmp_path: Path,
) -> None:
    def keys(archetype: str) -> set[str]:
        root = _config_root(tmp_path / archetype, archetype)
        return {a.key for a in DOCS.artifacts(KilnConfig.load(root), root)}

    assert not {k for k in keys("python-lib") if k.startswith("docs/reference/")}
    assert {"docs/reference/index.md", "docs/reference/_structure.md"} <= keys(
        "python-app"
    )
