"""S4.3.1 — the `python` module's artifacts: `.importlinter`.

Also proves the five properties every F4.3 story owes its module
(`docs/specs/epics/E4-generator/F4.3-concern-modules.md`).
"""

from __future__ import annotations

import re
from pathlib import Path

import pytest
from rn_forge.tooling.generation import Action, ArtifactKind

from rn_forge.kiln.config import KilnConfig
from rn_forge.kiln.modules.core import cycle
from rn_forge.kiln.modules.python import PYTHON

GOLDEN = Path(__file__).resolve().parents[2] / "fixtures" / "golden"
ARCHETYPES = ("python-app", "python-tool", "python-lib")

CONFIG = """
schema_version = 1

[repository]
name = "demo"
archetype = "{archetype}"
"""

LIB_CONFIG = """
schema_version = 1

[repository]
name = "demo"
archetype = "python-lib"

[archetype."python-lib"]
packages = ["packages/alpha", "packages/beta"]
"""


def _root(tmp_path: Path, archetype: str) -> Path:
    config = tmp_path / ".rn-forge" / "kiln" / "config.toml"
    config.parent.mkdir(parents=True)
    text = (
        LIB_CONFIG if archetype == "python-lib" else CONFIG.format(archetype=archetype)
    )
    config.write_text(text, encoding="utf-8")
    return tmp_path


@pytest.mark.parametrize("archetype", ARCHETYPES)
def test_s4_3_1_property1_renders_exactly_the_module_s_template_inventory_row(
    tmp_path: Path, archetype: str
) -> None:
    """The template inventory lists only `.importlinter` for `python`."""
    config = KilnConfig.load(_root(tmp_path, archetype))
    artifacts = PYTHON.artifacts(config, tmp_path)
    assert [a.path for a in artifacts] == [".importlinter"]
    assert artifacts[0].kind is ArtifactKind.MANAGED


@pytest.mark.parametrize("archetype", ARCHETYPES)
def test_s4_3_1_property2_into_an_empty_directory_only_creates(
    tmp_path: Path, archetype: str
) -> None:
    root = _root(tmp_path, archetype)
    home = tmp_path / "home"
    actions = {
        change.key: change.action for change in cycle.plan(root, home=home).changes
    }
    assert set(actions.values()) <= {Action.CREATE, Action.INSERT, Action.SKIP}
    assert actions[".importlinter"] is Action.CREATE


@pytest.mark.parametrize("archetype", ARCHETYPES)
def test_s4_3_1_property3_a_second_apply_is_unchanged(
    tmp_path: Path, archetype: str
) -> None:
    root = _root(tmp_path, archetype)
    home = tmp_path / "home"
    cycle.apply(root, home=home)
    actions = {
        change.key: change.action for change in cycle.plan(root, home=home).changes
    }
    assert set(actions.values()) <= {Action.UNCHANGED, Action.SKIP}


def _normalized(text: str) -> str:
    """Drop the provenance line's kiln version, the only line that never matches."""
    return re.sub(
        r"^; Generated by kiln .*$", "; Generated by kiln X", text, count=1, flags=re.M
    )


@pytest.mark.parametrize("archetype", ARCHETYPES)
def test_s4_3_1_property4_matches_its_golden_apart_from_the_provenance_line(
    archetype: str,
) -> None:
    config = KilnConfig.load(GOLDEN / archetype)
    [artifact] = PYTHON.artifacts(config, GOLDEN / archetype)
    rendered = _normalized(artifact.content)
    golden = _normalized(
        (GOLDEN / archetype / ".importlinter").read_text(encoding="utf-8")
    )
    assert rendered == golden


@pytest.mark.parametrize("archetype", ARCHETYPES)
def test_s4_3_1_3_lint_imports_passes_on_the_rendered_importlinter(
    tmp_path: Path, archetype: str, monkeypatch: pytest.MonkeyPatch
) -> None:
    """`lint-imports` passes on the rendered `.importlinter` in each archetype."""
    from importlinter import cli as importlinter_cli

    source = GOLDEN / archetype
    config = KilnConfig.load(source)
    [artifact] = PYTHON.artifacts(config, source)
    (tmp_path / ".importlinter").write_text(artifact.content, encoding="utf-8")

    src_dirs = (
        [str(source / "src")]
        if archetype != "python-lib"
        else [
            str(source / "packages" / "golden-alpha" / "src"),
            str(source / "packages" / "golden-beta" / "src"),
        ]
    )
    monkeypatch.chdir(tmp_path)
    for src_dir in src_dirs:
        monkeypatch.syspath_prepend(src_dir)
    assert (
        importlinter_cli.lint_imports(config_filename=str(tmp_path / ".importlinter"))
        == importlinter_cli.EXIT_STATUS_SUCCESS
    )


WEB_CONFIG = """
schema_version = 1

[repository]
name = "demo"
archetype = "{archetype}"

[archetype."{archetype}"]
backend = "{backend}"
{extra}
"""


def _web_root(tmp_path: Path, archetype: str, backend: str, extra: str = "") -> Path:
    config = tmp_path / ".rn-forge" / "kiln" / "config.toml"
    config.parent.mkdir(parents=True)
    config.write_text(
        WEB_CONFIG.format(archetype=archetype, backend=backend, extra=extra),
        encoding="utf-8",
    )
    return tmp_path


def test_s5_1_2_python_web_api_root_package_is_the_api_member(tmp_path: Path) -> None:
    root = _web_root(tmp_path, "python-web-api", "fastapi")
    config = KilnConfig.load(root)
    [artifact] = PYTHON.artifacts(config, root)
    assert "root_package = demo_api" in artifact.content


def test_s5_1_2_python_web_api_fastapi_forbids_django_not_fastapi(
    tmp_path: Path,
) -> None:
    root = _web_root(tmp_path, "python-web-api", "fastapi")
    config = KilnConfig.load(root)
    [artifact] = PYTHON.artifacts(config, root)
    forbidden = artifact.content.split("forbidden_modules =")[1].split(
        "allow_indirect"
    )[0]
    assert "django" in forbidden
    assert "fastapi" not in forbidden
    assert "typer" in forbidden
    assert "jinja2" in forbidden
    assert "click" in forbidden


def test_s5_1_2_python_web_app_django_forbids_fastapi_not_django(
    tmp_path: Path,
) -> None:
    root = _web_root(tmp_path, "python-web-app", "django", extra='frontend = "angular"')
    config = KilnConfig.load(root)
    [artifact] = PYTHON.artifacts(config, root)
    forbidden = artifact.content.split("forbidden_modules =")[1].split(
        "allow_indirect"
    )[0]
    assert "fastapi" in forbidden
    assert "django" not in forbidden


def test_s5_1_3_backend_flag_only_changes_the_importlinter_forbidden_list(
    tmp_path: Path,
) -> None:
    """`backend` never changes topology — only .importlinter's forbidden list."""
    django_root = _web_root(
        tmp_path / "django", "python-web-app", "django", extra='frontend = "angular"'
    )
    fastapi_root = _web_root(
        tmp_path / "fastapi", "python-web-app", "fastapi", extra='frontend = "angular"'
    )
    [django_artifact] = PYTHON.artifacts(KilnConfig.load(django_root), django_root)
    [fastapi_artifact] = PYTHON.artifacts(KilnConfig.load(fastapi_root), fastapi_root)
    django_lines = django_artifact.content.splitlines()
    fastapi_lines = fastapi_artifact.content.splitlines()
    assert len(django_lines) == len(fastapi_lines)
    diffs = [(a, b) for a, b in zip(django_lines, fastapi_lines, strict=True) if a != b]
    assert diffs == [("    fastapi", "    django")]
