"""Assert that a generated file's *body* is byte-identical across repos.

F2 in the standardization plan: `check_ci_entrypoint.py` was copied into four
repos and drifted into four forks that differed only by a list literal. The fix
is that the list is config — rendered into a fenced header — and the body below
it is the same bytes everywhere. This script is what makes that claim checkable
rather than aspirational.

    assert_generated_bodies.py --relative-path scripts/ci/check_ci_entrypoint.py REPO...
    assert_generated_bodies.py FILE FILE...

A body is the file minus its provenance line(s) and minus the
`# BEGIN kiln config` … `# END kiln config` block, inclusive. Everything else —
including the docstring and every comment — is compared byte for byte, because a
comment that has drifted is a fork that has not been noticed yet.

Exits 0 when every body hashes the same, 1 otherwise, printing each hash so the
odd one out is obvious.
"""

from __future__ import annotations

import argparse
import hashlib
import sys
from pathlib import Path

PROVENANCE_MARKERS = ("Generated by kiln",)
CONFIG_BEGIN = "BEGIN kiln config"
CONFIG_END = "END kiln config"


def is_provenance(line: str) -> bool:
    stripped = line.strip()
    if not stripped.startswith(("#", ";", "<!--")):
        return False
    return any(marker in stripped for marker in PROVENANCE_MARKERS)


def body(text: str) -> str:
    """The file with its provenance lines and config header removed."""
    kept: list[str] = []
    in_config = False
    for line in text.splitlines():
        if CONFIG_BEGIN in line:
            in_config = True
            continue
        if in_config:
            in_config = CONFIG_END not in line
            continue
        if is_provenance(line):
            continue
        kept.append(line)
    return "\n".join(kept)


def digest(text: str) -> str:
    return hashlib.sha256(text.encode("utf-8")).hexdigest()


def resolve(targets: list[str], relative_path: str | None) -> list[Path]:
    if relative_path is None:
        return [Path(target) for target in targets]
    return [Path(target) / relative_path for target in targets]


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--relative-path",
        default=None,
        help="path within each repo to compare; without it, targets are files",
    )
    parser.add_argument("targets", nargs="+", help="repo roots, or files")
    args = parser.parse_args()

    paths = resolve(args.targets, args.relative_path)
    missing = [path for path in paths if not path.is_file()]
    if missing:
        for path in missing:
            print(f"missing: {path}", file=sys.stderr)
        return 1

    hashes = {path: digest(body(path.read_text(encoding="utf-8"))) for path in paths}
    for path, value in hashes.items():
        print(f"{value}  {path}")

    distinct = set(hashes.values())
    if len(distinct) > 1:
        print(
            f"\n{len(distinct)} distinct bodies across {len(paths)} files — "
            f"these are forks, not one generated file",
            file=sys.stderr,
        )
        return 1

    print(f"\nOK: {len(paths)} file(s), one body")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
