# Generated by kiln golden from .rn-forge/kiln/config.toml — do not edit; run 'kiln apply'
"""Validate the docs tree against the area model the repo declares.

check_structure.py [--docs-root docs] [--json]

Checks only what is mechanically decidable: area scaffolding, file naming, ADR
numbering and status, link and anchor resolution, that no `_*.md` file is
referenced from a page that ships, and that the root instruction file points at
the docs rules. It does not judge prose, page length, or whether content sits in
the right area — that is review, and review is a runbook (kiln ADR-0006).

The area list comes from `docs/_areas.yml`, which kiln seeds and the repo then
owns (kiln ADR-0005). An area kiln has never heard of is valid here.
"""

from __future__ import annotations

import argparse
import json
import re
from pathlib import Path

from _common import Area, Finding, headings, is_external, links, load_areas

KEBAB_RE = re.compile(r"^[a-z0-9]+(-[a-z0-9]+)*\.md$")
ADR_RE = re.compile(r"^(\d{4})-[a-z0-9-]+\.md$")
EPIC_DIR_RE = re.compile(r"^E(\d+)-[a-z0-9-]+$")
FEATURE_FILE_RE = re.compile(r"^F(\d+)\.(\d+)-[a-z0-9-]+\.md$")
RELEASE_DIR_RE = re.compile(r"^release-(\d+)$")
STATUS_RE = re.compile(r"^\*\*Status:\*\*\s*(.+)$", re.MULTILINE)
ALLOWED_ADR_STATUS = re.compile(
    r"^(proposed|accepted|deprecated|superseded by ADR-\d{4})"
)


def clean_status(value: str) -> str:
    """Strip a trailing Markdown hard-line-break backslash (`accepted \\`)."""
    return value.strip().rstrip("\\").strip()


def content_pages(directory: Path) -> list[Path]:
    return sorted(
        path
        for path in directory.glob("*.md")
        if path.name != "index.md" and not path.name.startswith("_")
    )


def check_areas(areas: list[Area], docs_root: Path) -> list[Finding]:
    findings: list[Finding] = []
    for area in areas:
        if area.generated:
            continue
        target = docs_root / area.key
        if not target.is_dir():
            if not area.optional:
                findings.append(
                    Finding(str(target), "missing-area", f"{area.key}/ does not exist")
                )
            continue
        for required, rule in (
            ("_structure.md", "missing-structure-md"),
            ("index.md", "missing-index"),
        ):
            if not (target / required).exists():
                findings.append(
                    Finding(str(target), rule, f"{area.key}/ has no {required}")
                )
    return findings


def check_naming(areas: list[Area], docs_root: Path) -> list[Finding]:
    findings: list[Finding] = []

    for area in areas:
        area_dir = docs_root / area.key
        if area.generated or not area_dir.is_dir():
            continue
        for path in content_pages(area_dir):
            if area.key == "adr":
                continue
            if not KEBAB_RE.match(path.name):
                findings.append(Finding(str(path), "kebab-case", "not kebab-case"))

    adr_dir = docs_root / "adr"
    if adr_dir.is_dir():
        numbers: list[int] = []
        for path in content_pages(adr_dir):
            match = ADR_RE.match(path.name)
            if not match:
                findings.append(
                    Finding(str(path), "adr-naming", "does not match <nnnn>-<slug>.md")
                )
                continue
            numbers.append(int(match.group(1)))
        if len(numbers) != len(set(numbers)):
            findings.append(
                Finding(str(adr_dir), "adr-duplicate-number", "duplicate ADR numbers")
            )
        for expected, actual in enumerate(sorted(set(numbers)), start=1):
            if expected != actual:
                findings.append(
                    Finding(
                        str(adr_dir),
                        "adr-number-gap",
                        f"expected {expected:04d}, found {actual:04d}",
                    )
                )
                break

    releases_dir = docs_root / "releases"
    if releases_dir.is_dir():
        for path in sorted(p for p in releases_dir.iterdir() if p.is_dir()):
            if not RELEASE_DIR_RE.match(path.name):
                findings.append(
                    Finding(str(path), "release-naming", "does not match release-<n>/")
                )
            elif not (path / "index.md").exists():
                findings.append(
                    Finding(
                        str(path),
                        "release-missing-index",
                        "release-<n>/ has no index.md",
                    )
                )

    epics_dir = docs_root / "specs" / "epics"
    if epics_dir.is_dir():
        for path in sorted(p for p in epics_dir.iterdir() if p.is_dir()):
            if not EPIC_DIR_RE.match(path.name):
                findings.append(
                    Finding(str(path), "epic-naming", "does not match E<n>-<slug>/")
                )
            for feature_path in sorted(path.glob("F*.md")):
                if not FEATURE_FILE_RE.match(feature_path.name):
                    findings.append(
                        Finding(
                            str(feature_path),
                            "feature-naming",
                            "does not match F<n>.<m>-<slug>.md",
                        )
                    )

    return findings


def check_adr_status(docs_root: Path) -> list[Finding]:
    adr_dir = docs_root / "adr"
    if not adr_dir.is_dir():
        return []
    findings: list[Finding] = []
    for path in content_pages(adr_dir):
        match = STATUS_RE.search(path.read_text(encoding="utf-8"))
        if not match or not ALLOWED_ADR_STATUS.match(
            clean_status(match.group(1)).lower()
        ):
            findings.append(
                Finding(str(path), "adr-status", "missing or invalid **Status:** line")
            )
    return findings


def link_target(source: Path, link: str) -> tuple[Path | None, str]:
    target, _, anchor = link.partition("#")
    return ((source.parent / target).resolve() if target else None), anchor


def check_links(docs_root: Path) -> list[Finding]:
    findings: list[Finding] = []
    for path in sorted(docs_root.rglob("*.md")):
        text = path.read_text(encoding="utf-8")
        for link in links(text):
            if is_external(link):
                continue
            resolved, anchor = link_target(path, link)
            if resolved is None:
                if anchor and anchor not in headings(text):
                    findings.append(
                        Finding(
                            str(path),
                            "broken-anchor",
                            f"#{anchor} not found in same page",
                        )
                    )
                continue
            if not resolved.exists():
                findings.append(
                    Finding(str(path), "broken-link", f"{link} does not resolve")
                )
                continue
            if (
                anchor
                and resolved.suffix == ".md"
                and anchor not in headings(resolved.read_text(encoding="utf-8"))
            ):
                findings.append(
                    Finding(str(path), "broken-anchor", f"{link} anchor not found")
                )
    return findings


def check_no_underscore_refs(docs_root: Path) -> list[Finding]:
    findings: list[Finding] = []
    for path in sorted(docs_root.rglob("*.md")):
        if path.name.startswith("_"):
            continue
        for link in links(path.read_text(encoding="utf-8")):
            name = Path(link.partition("#")[0]).name
            if name.startswith("_") and not name.startswith("__"):
                findings.append(
                    Finding(str(path), "underscore-referenced", f"links to {link}")
                )
    return findings


INSTRUCTION_FILES = ("CLAUDE.md", "AGENTS.md")


def resolved_links(path: Path) -> set[Path]:
    return {
        (path.parent / link.partition("#")[0]).resolve()
        for link in links(path.read_text(encoding="utf-8"))
        if not is_external(link)
    }


def check_instruction_pointer(repo_root: Path, docs_root: Path) -> list[Finding]:
    """Some instruction file must link both `docs/_structure.md` and
    `docs/index.md`, and every other one must reach it.

    That is the only route into the rules for a session that has read neither
    kiln nor this script (agentkit ADR-0018). It is deliberately not "every
    instruction file links both": instructions are single-sourced (agentkit
    ADR-0011), so `AGENTS.md` is a pointer at `CLAUDE.md` rather than a second
    copy that can drift. What matters is that following the links from whichever
    file an agent opened first arrives at the rules.
    """
    present = [
        repo_root / name for name in INSTRUCTION_FILES if (repo_root / name).exists()
    ]
    if not present:
        return [
            Finding(
                str(repo_root),
                "missing-instruction-file",
                f"no instruction file: expected one of {', '.join(INSTRUCTION_FILES)}",
            )
        ]

    wanted = {
        (docs_root / target).resolve() for target in ("_structure.md", "index.md")
    }
    carriers = [path for path in present if wanted <= resolved_links(path)]
    if not carriers:
        return [
            Finding(
                str(path),
                "missing-docs-pointer",
                f"no instruction file links both {docs_root.name}/_structure.md "
                f"and {docs_root.name}/index.md",
            )
            for path in present
        ]

    carrier_paths = {path.resolve() for path in carriers}
    return [
        Finding(
            str(path),
            "missing-docs-pointer",
            f"neither links the docs rules nor points at "
            f"{', '.join(sorted(p.name for p in carrier_paths))}",
        )
        for path in present
        if path.resolve() not in carrier_paths
        and not (resolved_links(path) & carrier_paths)
    ]


def run_all(repo_root: Path, docs_root: Path) -> list[Finding]:
    try:
        areas = load_areas(docs_root)
    except (FileNotFoundError, ValueError) as exc:
        return [Finding(str(docs_root), "areas-manifest", str(exc))]

    return [
        *check_areas(areas, docs_root),
        *check_naming(areas, docs_root),
        *check_adr_status(docs_root),
        *check_links(docs_root),
        *check_no_underscore_refs(docs_root),
        *check_instruction_pointer(repo_root, docs_root),
    ]


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--docs-root", default="docs")
    parser.add_argument("--json", action="store_true")
    args = parser.parse_args()

    docs_root = Path(args.docs_root)
    findings = run_all(docs_root.resolve().parent, docs_root)

    if args.json:
        print(json.dumps({"findings": [finding.to_dict() for finding in findings]}))
    else:
        for finding in findings:
            print(f"{finding.path}: [{finding.rule}] {finding.message}")

    return 1 if findings else 0


if __name__ == "__main__":
    raise SystemExit(main())
