# Generated by kiln golden from .rn-forge/kiln/config.toml — do not edit; run 'kiln apply'
"""Generate `mkdocs.yml`'s `nav:` block from `docs/_areas.yml` and the tree.

gen_nav.py [--check] [--mkdocs mkdocs.yml] [--docs-root docs]

Rewrites the block between `# BEGIN generated nav` and `# END generated nav`.
`--check` exits non-zero when the generated block differs from what is on disk
without writing anything — that is the form `task lint` runs. Content outside
the markers is preserved byte for byte, because `mkdocs.yml` is a repo-owned
file with one kiln-owned block in it (kiln ADR-0001).

Page order inside an area is: the area's `index.md` first, then the pages its
`index.md` links to in the order it links them, then everything else
alphabetically. An index page is therefore how a human overrides nav order,
which keeps ordering out of the config file.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

from _common import Area, is_external, links, load_areas

BEGIN_MARKER = "  # BEGIN generated nav"
END_MARKER = "  # END generated nav"

ACRONYMS = {"adr": "ADR", "api": "API", "cli": "CLI", "ci": "CI", "id": "ID"}


def title_from_filename(name: str) -> str:
    stem = name.removesuffix(".md")
    return " ".join(
        ACRONYMS.get(word.lower(), word.capitalize()) for word in stem.split("-")
    )


def linked_order(index_path: Path) -> list[str]:
    if not index_path.exists():
        return []
    return [
        link.partition("#")[0]
        for link in links(index_path.read_text(encoding="utf-8"))
        if not is_external(link) and link.partition("#")[0].endswith(".md")
    ]


def children_entries(docs_root: Path, area_key: str) -> list[tuple[str, str]]:
    area_dir = docs_root / area_key
    index_path = area_dir / "index.md"

    ordered: list[str] = []
    if index_path.exists():
        ordered.append(f"{area_key}/index.md")
    for link in linked_order(index_path):
        rel = link if link.startswith(f"{area_key}/") else f"{area_key}/{link}"
        if (docs_root / rel).exists() and rel not in ordered:
            ordered.append(rel)
    for page in sorted(area_dir.glob("*.md")):
        rel = f"{area_key}/{page.name}"
        if page.name == "index.md" or page.name.startswith("_") or rel in ordered:
            continue
        ordered.append(rel)

    return [
        (
            "Overview"
            if Path(rel).name == "index.md"
            else title_from_filename(Path(rel).name),
            rel,
        )
        for rel in ordered
    ]


def area_lines(docs_root: Path, area: Area) -> list[str]:
    area_dir = docs_root / area.key
    if (area.optional or area.generated) and not area_dir.is_dir():
        return []
    if area.nav == "index-only":
        return [f"  - {area.title}: {area.key}/index.md"]
    entries = children_entries(docs_root, area.key)
    if not entries:
        return []
    return [f"  - {area.title}:"] + [
        f"      - {title}: {rel}" for title, rel in entries
    ]


def build_nav_lines(docs_root: Path) -> list[str]:
    lines = [BEGIN_MARKER, "  - Home: index.md"]
    for area in load_areas(docs_root):
        lines.extend(area_lines(docs_root, area))
    lines.append(END_MARKER)
    return lines


def render(mkdocs_text: str, nav_lines: list[str]) -> str:
    lines = mkdocs_text.splitlines()
    begin_index: int | None = None
    end_index: int | None = None
    for index, line in enumerate(lines):
        if line.strip() == BEGIN_MARKER.strip():
            begin_index = index
        elif line.strip() == END_MARKER.strip():
            end_index = index
    if begin_index is None or end_index is None:
        raise ValueError(
            "mkdocs.yml has no '# BEGIN generated nav' / '# END generated nav' markers"
        )
    return "\n".join(lines[:begin_index] + nav_lines + lines[end_index + 1 :]) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--mkdocs", default="mkdocs.yml")
    parser.add_argument("--docs-root", default="docs")
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()

    mkdocs_path = Path(args.mkdocs)
    if not mkdocs_path.exists():
        print(f"error: {mkdocs_path} not found", file=sys.stderr)
        return 1

    try:
        new_text = render(
            mkdocs_path.read_text(encoding="utf-8"),
            build_nav_lines(Path(args.docs_root)),
        )
    except (FileNotFoundError, ValueError) as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 1

    current_text = mkdocs_path.read_text(encoding="utf-8")

    if args.check:
        if new_text != current_text:
            print("mkdocs.yml nav is stale; run `task docs:nav`", file=sys.stderr)
            return 1
        print("nav is up to date")
        return 0

    if new_text != current_text:
        mkdocs_path.write_text(new_text, encoding="utf-8")
        print(f"updated {mkdocs_path}")
    else:
        print("no change")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
