# docs/ — what belongs here

The rules for the tree as a whole: which area a statement belongs in, and where
new material goes. `docs/index.md` is the reader's entry point; this file is the
agent's — they are not copies of each other.

## Belongs here

- The area table below, and nothing about any one area's content.
- The "where new material goes" routing rule.

## Does not belong here

| Instead of | Put it in |
| -- | -- |
| A statement about one area's admission rules | that area's own `_structure.md` |
| Page content | the area itself |

## Naming and shape

- Areas, in nav order: `architecture/`, `guides/`, `runbooks/` (optional),
  `reference/` (generated), `releases/`, `specs/`, `adr/`.
- Every area's rules live in its own `_structure.md`; this file only lists them.
- `_*.md` files never ship in the built site (`exclude_docs: "_*"`).
- `mkdocs.yml`'s `nav:` is generated by `kiln docs-nav` from `docs/_areas.yml`
  and the tree — do not hand-edit it; run `task docs:nav` after adding a page.
- Adding an area is an edit to `docs/_areas.yml`, which kiln seeds and this repo
  owns. Nothing in kiln needs to change for it.

## Where new material goes

- Behaviour as it is now → `architecture/`, or `guides/` if it is about using
  the tool. Never duplicated into a spec.
- A choice between real alternatives → a new ADR under `adr/`; a change to one →
  that ADR, revised in place.
- Work to do, or a record of work done → an epic under `specs/epics/`.
- What ships when → `releases/`.
- An operational procedure → `runbooks/`.
- An open question → the epic or feature it blocks, until it becomes an ADR or a
  rejected option recorded there.

## Checks

`kiln doctor --only docs-structure` enforces kiln's docs policy: every
non-optional area in `docs/_areas.yml` exists and has both a `_structure.md` and
an `index.md`; ADRs are named `ADR-<nnnn>.md`, numbered without gaps, and carry
a valid `**Status:**` line; every relative link resolves, including anchors; no
shipped page links to a `_*.md` file; and `CLAUDE.md`/`AGENTS.md` both point at
this file and at `docs/index.md`.

## Keeping it honest

Check for these when changing the tree, and report what you find rather than
fixing it silently — some of it is deliberate:

- A release names a story ID that does not exist, or a planned story is in no
  release.
- An epic's status contradicts its stories, or its board row is in the wrong
  group, or in two.
- Two ADRs decide the same topic, or an ADR's Decision changed
  (`git log --follow docs/adr/ADR-<nnnn>.md`) with no History entry saying so.
- Design prose collecting in a top-level page instead of under its feature.
- A `progress.md`, `backlog.md`, `decisions.md` or `overview.md` has appeared;
  each restates what the epics, deferred epics, ADRs or README already own.
- `README.md`, `CLAUDE.md` or `AGENTS.md` describing the tree instead of linking
  to it. `CLAUDE.md` links to the specs board and the ADR log and says what
  each is for; `AGENTS.md` points at `CLAUDE.md`.
- A `README.md` inside `docs/`: MkDocs drops one that sits beside an `index.md`,
  and the strict build fails.
